package content

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
)

// chroma is imported here and nowhere else on purpose.
//
// A test-only import is compiled into the test binary and never into the
// worker, which is the whole reason the highlighting is generated rather than
// done at render time. Moving any of this into a non-test file puts 1 MB of
// embedded lexers back into the WebAssembly module.

var update = flag.Bool("update", false, "rewrite content/highlighted_gen.go")

// styleName is the theme the TSX site used, via shiki's "tokyo-night".
const (
	styleName      = "tokyonight-night"
	lightStyleName = "tokyonight-day"
)

// lexerFor maps a declared language onto a chroma lexer. templ is Go with HTML
// in it and no lexer knows it; the old site made the same substitution.
func lexerFor(lang string) chroma.Lexer {
	switch lang {
	case "templ":
		lang = "go"
	case "text", "":
		return nil
	}
	return lexers.Get(lang)
}

func render(lang, src string) (string, error) {
	lexer := lexerFor(lang)
	if lexer == nil {
		return "", nil // plain text: the renderer escapes it itself
	}
	iterator, err := lexer.Tokenise(nil, src)
	if err != nil {
		return "", err
	}
	formatter := chromahtml.New(
		chromahtml.WithClasses(true),
		chromahtml.PreventSurroundingPre(true),
	)
	var buf bytes.Buffer
	if err := formatter.Format(&buf, styles.Get(styleName), iterator); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// TestHighlightingIsCurrent regenerates the highlighting with -update, and
// otherwise fails when the checked-in file no longer matches the samples.
//
// Without this, editing a code sample silently drops its colouring: the
// renderer falls back to plain text and the page still looks fine at a glance.
func TestHighlightingIsCurrent(t *testing.T) {
	want := map[string]string{}
	for _, p := range Pages {
		for _, b := range p.Blocks {
			if b.Kind != KindCode {
				continue
			}
			html, err := render(b.Lang, b.Text)
			if err != nil {
				t.Fatalf("%s: highlighting %q: %v", p.Slug, b.Lang, err)
			}
			if html == "" {
				continue // plain text needs no entry
			}
			want[CodeKey(b.Lang, b.Text)] = html
		}
	}
	for name, s := range Samples {
		html, err := render(s.Lang, s.Text)
		if err != nil {
			t.Fatalf("%s: highlighting %q: %v", name, s.Lang, err)
		}
		if html != "" {
			want[CodeKey(s.Lang, s.Text)] = html
		}
	}

	if *update {
		writeGenerated(t, want)
		writeCSS(t)
		t.Logf("wrote %d highlighted samples", len(want))
		return
	}

	for key, html := range want {
		got, ok := highlighted[key]
		if !ok {
			t.Errorf("no highlighting for %s — run: go test ./content -run TestHighlightingIsCurrent -update", key)
			continue
		}
		if got != html {
			t.Errorf("highlighting for %s is stale — run with -update", key)
		}
	}
	for key := range highlighted {
		if _, ok := want[key]; !ok {
			t.Errorf("highlighting for %s belongs to no sample — run with -update", key)
		}
	}
}

// TestEveryCodeBlockIsHighlighted is the reader-facing half: a sample in a
// language we highlight must actually arrive highlighted.
func TestEveryCodeBlockIsHighlighted(t *testing.T) {
	for _, p := range Pages {
		for _, b := range p.Blocks {
			if b.Kind != KindCode || lexerFor(b.Lang) == nil {
				continue
			}
			if _, ok := Highlighted(b.Lang, b.Text); !ok {
				t.Errorf("%s: a %s sample is not highlighted", p.Slug, b.Lang)
			}
		}
	}
	for name, s := range Samples {
		if lexerFor(s.Lang) == nil {
			continue
		}
		if _, ok := Highlighted(s.Lang, s.Text); !ok {
			t.Errorf("sample %q is not highlighted", name)
		}
	}
}

func writeGenerated(t *testing.T, entries map[string]string) {
	t.Helper()

	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go test ./content -run TestHighlightingIsCurrent -update. DO NOT EDIT.\n\n")
	buf.WriteString("package content\n\n")
	buf.WriteString("// highlighted maps CodeKey to the markup chroma produced for that sample.\n")
	buf.WriteString("var highlighted = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%s: %s,\n", strconv.Quote(k), strconv.Quote(entries[k]))
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		t.Fatalf("formatting generated source: %v", err)
	}
	if err := os.WriteFile("highlighted_gen.go", src, 0o644); err != nil {
		t.Fatal(err)
	}
}

// writeCSS emits the token colours as a stylesheet, so the markup carries
// class names rather than a style attribute on every span.
//
// Two themes, because the documentation pages follow the reader's colour
// scheme and a dark syntax theme on a white page is unreadable — pale blue on
// white, which is what shipped until someone looked at it in light mode. The
// light rules are scoped to the docs shell: the landing and demo pages are
// dark whatever the system says, so their code blocks must stay dark too.
func writeCSS(t *testing.T) {
	t.Helper()
	formatter := chromahtml.New(chromahtml.WithClasses(true))

	var buf bytes.Buffer
	buf.WriteString("/* Generated by go test ./content -run TestHighlightingIsCurrent -update.\n")
	buf.WriteString("   " + styleName + " for dark, " + lightStyleName + " for light. */\n")

	if err := formatter.WriteCSS(&buf, styles.Get(styleName)); err != nil {
		t.Fatal(err)
	}

	var light bytes.Buffer
	if err := formatter.WriteCSS(&light, styles.Get(lightStyleName)); err != nil {
		t.Fatal(err)
	}
	buf.WriteString("\n@media (prefers-color-scheme: light) {\n")
	for _, line := range strings.Split(strings.TrimSpace(light.String()), "\n") {
		buf.WriteString("  " + scopeToDocs(line) + "\n")
	}
	buf.WriteString("}\n")

	if err := os.WriteFile("../static/css/chroma.css", buf.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}
}

// scopeToDocs prefixes a chroma rule so it applies only inside the
// documentation shell.
func scopeToDocs(line string) string {
	i := strings.Index(line, "{")
	if i < 0 {
		return line
	}
	selectors, body := line[:i], line[i:]

	// Rules can carry a leading /* comment */ that is not part of the selector.
	var prefix string
	if j := strings.LastIndex(selectors, "*/"); j >= 0 {
		prefix, selectors = selectors[:j+2], selectors[j+2:]
	}

	var out []string
	for _, sel := range strings.Split(selectors, ",") {
		sel = strings.TrimSpace(sel)
		if sel == "" {
			continue
		}
		out = append(out, ".docs-main "+sel)
	}
	return prefix + " " + strings.Join(out, ", ") + " " + body
}
