// The documentation prose, ported from the TSX site.
//
// Content is data rather than markup for the same reason the CLI reference is:
// one renderer, one place to edit, and a page cannot be half-styled because
// somebody wrote different markup on it. The CLI reference is not here — it is
// generated from the binary, which is the whole point of that page.
//
// The block kinds and the inline markup prose may use are in block.go.
package content

// Page is a documentation page.
type Page struct {
	Slug   string
	Title  string
	Blocks []Block
}

// Pages is every prose page, in the order the navigation lists them.
var Pages = []Page{
	{
		Slug:  "introduction",
		Title: "Introduction",
		Blocks: []Block{
			P("**irgo** is a hypermedia-driven application framework that uses Go as a runtime kernel with Datastar. Build native iOS, Android, and desktop apps using Go, HTML, and Datastar - no JavaScript frameworks required."),
			H2("The Hypermedia Approach"),
			P("Unlike traditional mobile and desktop frameworks that require learning platform-specific languages and UI toolkits, irgo takes a different approach: **HTML is your UI layer**."),
			P("Your Go code renders HTML templates. Datastar handles interactivity using Server-Sent Events (SSE) to stream HTML updates to the browser. The framework handles the rest - whether that's routing requests through a native bridge on mobile or serving them over HTTP on desktop."),
			CodeFile("text", "The irgo pattern", "User Interaction \u2192 Datastar Request \u2192 Go Handler \u2192 SSE Response \u2192 DOM Morph"),
			H2("Key Features"),
			Bullets(
				"**Go-Powered Apps**: Write your backend logic in Go, compile to native mobile frameworks or desktop apps",
				"**Datastar for Interactivity**: Use Datastar's SSE-based hypermedia approach instead of complex JavaScript",
				"**Cross-Platform**: Single codebase for iOS, Android, desktop (macOS, Windows, Linux), and web",
				"**Virtual HTTP (Mobile)**: No network sockets - requests are intercepted and handled directly by Go",
				"**Native Webview (Desktop)**: Real HTTP server with native webview window",
				"**Type-Safe Templates**: Use [templ](https://templ.guide) for compile-time checked HTML templates",
				"**Hot Reload Development**: Edit Go/templ code and see changes instantly",
			),
			H2("Platform Support"),
			P("irgo supports four deployment modes:"),
			Table(
				[]string{"Platform", "Architecture", "Build Tag"},
				[]string{"iOS", "Virtual HTTP via gomobile bridge", "`!desktop`"},
				[]string{"Android", "Virtual HTTP via gomobile bridge", "`!desktop`"},
				[]string{"Desktop", "Real HTTP server + native webview", "`desktop`"},
				[]string{"Web", "Standard HTTP server", "`!desktop`"},
			),
			H2("Prerequisites"),
			P("Before getting started, make sure you have:"),
			Bullets(
				"Go 1.21 or later",
				"[templ](https://templ.guide): `go install github.com/a-h/templ/cmd/templ@latest`",
				"[air](https://github.com/air-verse/air) (for hot reload): `go install github.com/air-verse/air@latest`",
			),
			Note("info", "Platform-specific requirements",
				"**Mobile:** Xcode for iOS; the Android toolchain installs itself (Android)",
				"**Desktop:** CGO enabled with a C compiler (Xcode CLI on macOS, MinGW on Windows, GCC on Linux)",
			),
			H2("Quick Example"),
			P("Here's a taste of what irgo code looks like:"),
			CodeFile("go", "handlers/hello.go", "package handlers\n\nimport (\n    \"myapp/templates\"\n    \"github.com/stukennedy/irgo/pkg/router\"\n)\n\nfunc Hello(ctx *router.Context) error {\n    var signals struct {\n        Name string `json:\"name\"`\n    }\n    ctx.ReadSignals(&signals)\n\n    if signals.Name == \"\" {\n        signals.Name = \"World\"\n    }\n\n    return ctx.SSE().PatchTempl(templates.Greeting(signals.Name))\n}"),
			CodeFile("templ", "templates/greeting.templ", "package templates\n\ntempl Greeting(name string) {\n    <div id=\"greeting\" class=\"greeting\" data-signals=\"{name: ''}\">\n        <h1>Hello, { name }!</h1>\n        <input\n            type=\"text\"\n            data-bind:name\n            placeholder=\"Enter a name\"\n        />\n        <button data-on:click=\"@get('/hello')\">Greet</button>\n    </div>\n}"),
			H2("AI Coding Assistants"),
			P("If you're using an AI coding assistant (like Claude, Cursor, or GitHub Copilot), point it to our [llms.txt](/llms.txt) file. This provides comprehensive instructions for writing irgo applications, including handler patterns, templ syntax, Datastar integration, and SSE responses."),
			H2("Next Steps"),
			P("Ready to build your first irgo app? Head to the [Quick Start](/docs/getting-started) guide."),
		},
	},
	{
		Slug:  "getting-started",
		Title: "Getting started",
		Blocks: []Block{
			P("This guide will walk you through creating your first irgo application, running it in development mode, and building it for different platforms."),
			H2("Install the CLI"),
			P("Install the irgo CLI using Go:"),
			Code("bash", "go install github.com/stukennedy/irgo/cmd/irgo@latest"),
			P("Or build from source:"),
			Code("bash", "git clone https://github.com/stukennedy/irgo.git\ncd irgo/cmd/irgo\ngo install ."),
			P("Verify the installation:"),
			Code("bash", "irgo version"),
			H2("Create a New Project"),
			Code("bash", "irgo project new myapp\ncd myapp\ngo mod tidy"),
			P("This creates a new project with the following structure:"),
			Code("text", "myapp/\n\u251c\u2500\u2500 main.go              # Mobile/web entry point\n\u251c\u2500\u2500 main_desktop.go      # Desktop entry point\n\u251c\u2500\u2500 go.mod               # Go module definition\n\u251c\u2500\u2500 .air.toml            # Hot reload configuration\n\u251c\u2500\u2500 app/\n\u2502   \u2514\u2500\u2500 app.go           # Router setup\n\u251c\u2500\u2500 handlers/\n\u2502   \u2514\u2500\u2500 handlers.go      # HTTP handlers\n\u251c\u2500\u2500 templates/\n\u2502   \u251c\u2500\u2500 layout.templ     # Base HTML layout\n\u2502   \u251c\u2500\u2500 home.templ       # Home page template\n\u2502   \u2514\u2500\u2500 components.templ # Reusable components\n\u2514\u2500\u2500 static/\n    \u251c\u2500\u2500 css/\n    \u2502   \u251c\u2500\u2500 input.css    # Tailwind source\n    \u2502   \u2514\u2500\u2500 output.css   # Generated CSS\n    \u2514\u2500\u2500 js/\n        \u2514\u2500\u2500 datastar.js  # Datastar library (downloaded automatically)"),
			H2("Development Mode"),
			H3("Web Development (Hot Reload)"),
			Code("bash", "irgo server dev"),
			P("This starts a development server at `http://localhost:8080` with hot reload. Edit your Go or templ files and see changes instantly."),
			H3("Desktop Development"),
			Code("bash", "irgo app run desktop         # Run as desktop app\nirgo app run desktop --dev   # With browser devtools enabled"),
			H3("iOS Development"),
			Code("bash", "irgo app run ios --dev       # Hot reload with iOS Simulator\nirgo app run ios             # Production build"),
			H3("Android Development"),
			Code("bash", "irgo app run android --dev   # Hot reload with Android Emulator\nirgo app run android         # Production build"),
			H2("Building for Production"),
			H3("Desktop"),
			Code("bash", "irgo app build desktop           # Build for current platform\nirgo app build desktop macos     # Build macOS .app bundle\nirgo app build desktop windows   # Build Windows .exe\nirgo app build desktop linux     # Build Linux binary"),
			H3("Mobile"),
			Code("bash", "irgo app build ios               # Build iOS framework\nirgo app build android           # Build Android AAR\nirgo app build all               # Build for all mobile platforms"),
			H2("Your First Handler"),
			P("Let's create a simple counter to understand the irgo pattern."),
			H3("1. Create the Handler"),
			CodeFile("go", "handlers/counter.go", "package handlers\n\nimport (\n    \"myapp/templates\"\n    \"github.com/stukennedy/irgo/pkg/router\"\n)\n\nvar count = 0\n\nfunc GetCounter(ctx *router.Context) error {\n    return ctx.SSE().PatchTempl(templates.Counter(count))\n}\n\nfunc IncrementCounter(ctx *router.Context) error {\n    count++\n    return ctx.SSE().PatchTempl(templates.Counter(count))\n}\n\nfunc DecrementCounter(ctx *router.Context) error {\n    count--\n    return ctx.SSE().PatchTempl(templates.Counter(count))\n}"),
			H3("2. Create the Template"),
			CodeFile("templ", "templates/counter.templ", "package templates\n\nimport \"fmt\"\n\ntempl Counter(count int) {\n    <div id=\"counter\" class=\"counter\">\n        <h2>Count: { fmt.Sprintf(\"%d\", count) }</h2>\n        <div class=\"buttons\">\n            <button data-on:click=\"@post('/counter/decrement')\">-</button>\n            <button data-on:click=\"@post('/counter/increment')\">+</button>\n        </div>\n    </div>\n}"),
			H3("3. Register the Routes"),
			CodeFile("go", "app/app.go", "package app\n\nimport (\n    \"myapp/handlers\"\n    \"github.com/stukennedy/irgo/pkg/router\"\n)\n\nfunc NewRouter() *router.Router {\n    r := router.New()\n\n    // Counter routes (DS prefix for Datastar SSE handlers)\n    r.DSGet(\"/counter\", handlers.GetCounter)\n    r.DSPost(\"/counter/increment\", handlers.IncrementCounter)\n    r.DSPost(\"/counter/decrement\", handlers.DecrementCounter)\n\n    return r\n}"),
			H3("4. Generate Templates and Run"),
			Code("bash", "irgo project assets      # Generate _templ.go files\nirgo server dev        # Start development server"),
			P("Visit `http://localhost:8080/counter` - you now have a working counter with Datastar-powered interactions!"),
			Note("tip", "",
				"Notice how the handler uses SSE to stream HTML updates. Datastar morphs the `#counter` element with the new HTML. This is the hypermedia pattern at work.",
			),
			H2("Next Steps"),
			Bullets(
				"[Project Structure](/docs/project-structure) - Understand how irgo projects are organized",
				"[Routing & Handlers](/docs/routing) - Learn about the router and context API",
				"[Templ Templates](/docs/templates) - Master the templating language",
				"[Datastar Integration](/docs/datastar) - Explore Datastar patterns in irgo",
			),
		},
	},
	{
		Slug:  "project-structure",
		Title: "Project structure",
		Blocks: []Block{
			P("An irgo project follows a clean, conventional structure that separates concerns while keeping related code together."),
			H2("Directory Layout"),
			Code("text", "myapp/\n\u251c\u2500\u2500 main.go              # Mobile/web entry point (build tag: !desktop)\n\u251c\u2500\u2500 main_desktop.go      # Desktop entry point (build tag: desktop)\n\u251c\u2500\u2500 go.mod               # Module, dependencies, and the irgo the project uses\n\u251c\u2500\u2500 .air.toml            # Air hot reload configuration\n\u251c\u2500\u2500 appicon.png          # One source icon; every platform's icons come from it\n\u251c\u2500\u2500 irgo.package.toml    # Signing and store settings\n\u251c\u2500\u2500 .github/workflows/   # CI for every target, generated by the CLI\n\u2502\n\u251c\u2500\u2500 app/\n\u2502   \u2514\u2500\u2500 app.go           # Router setup and app configuration\n\u2502\n\u251c\u2500\u2500 handlers/\n\u2502   \u2514\u2500\u2500 handlers.go      # HTTP handlers (business logic)\n\u2502\n\u251c\u2500\u2500 templates/\n\u2502   \u251c\u2500\u2500 layout.templ     # Base HTML layout\n\u2502   \u251c\u2500\u2500 home.templ       # Home page template\n\u2502   \u2514\u2500\u2500 components.templ # Reusable components\n\u2502\n\u251c\u2500\u2500 static/\n\u2502   \u251c\u2500\u2500 css/\n\u2502   \u2502   \u251c\u2500\u2500 input.css    # Tailwind source\n\u2502   \u2502   \u2514\u2500\u2500 output.css   # Generated CSS\n\u2502   \u2514\u2500\u2500 js/\n\u2502       \u2514\u2500\u2500 datastar.js  # Datastar library (downloaded automatically)\n\u2502\n\u251c\u2500\u2500 mobile/\n\u2502   \u2514\u2500\u2500 mobile.go        # Mobile bridge setup\n\u2502\n\u251c\u2500\u2500 ios/                 # iOS Xcode project\n\u251c\u2500\u2500 android/             # Android project\n\u2502\n\u2514\u2500\u2500 build/\n    \u251c\u2500\u2500 ios/             # Built iOS framework\n    \u251c\u2500\u2500 android/         # Built Android AAR\n    \u2514\u2500\u2500 desktop/         # Built desktop apps\n        \u251c\u2500\u2500 macos/       # macOS .app bundle\n        \u251c\u2500\u2500 windows/     # Windows .exe\n        \u2514\u2500\u2500 linux/       # Linux binary"),
			H2("Entry Points"),
			P("irgo uses Go build tags to separate platform-specific entry points:"),
			H3("Mobile/Web Entry Point"),
			CodeFile("go", "main.go", "//go:build !desktop\n\npackage main\n\nimport (\n    \"fmt\"\n    \"log\"\n    \"net/http\"\n    \"os\"\n\n    \"myapp/app\"\n    \"github.com/stukennedy/irgo/mobile\"\n)\n\nfunc main() {\n    // If run with \"serve\" argument, start web dev server\n    if len(os.Args) > 1 && os.Args[1] == \"serve\" {\n        runDevServer()\n        return\n    }\n    // Otherwise, initialize for mobile\n    initMobile()\n}\n\nfunc initMobile() {\n    mobile.Initialize()\n    r := app.NewRouter()\n    mobile.SetHandler(r.Handler())\n    fmt.Println(\"Mobile app initialized\")\n}\n\nfunc runDevServer() {\n    r := app.NewRouter()\n    mux := http.NewServeMux()\n    mux.Handle(\"/static/\", http.StripPrefix(\"/static/\",\n        http.FileServer(http.Dir(\"static\"))))\n    mux.Handle(\"/\", r.Handler())\n\n    fmt.Println(\"Dev server at http://localhost:8080\")\n    log.Fatal(http.ListenAndServe(\":8080\", mux))\n}"),
			H3("Desktop Entry Point"),
			CodeFile("go", "main_desktop.go", "//go:build desktop\n\npackage main\n\nimport (\n    \"flag\"\n    \"fmt\"\n    \"net/http\"\n\n    \"myapp/app\"\n    \"github.com/stukennedy/irgo/desktop\"\n)\n\nfunc main() {\n    devMode := flag.Bool(\"dev\", false, \"Enable devtools\")\n    flag.Parse()\n\n    r := app.NewRouter()\n\n    mux := http.NewServeMux()\n    staticDir := desktop.FindStaticDir()\n    mux.Handle(\"/static/\", http.StripPrefix(\"/static/\",\n        http.FileServer(http.Dir(staticDir))))\n    mux.Handle(\"/\", r.Handler())\n\n    config := desktop.DefaultConfig()\n    config.Title = \"My App\"\n    config.Debug = *devMode\n\n    desktopApp := desktop.New(mux, config)\n\n    fmt.Println(\"Starting desktop app...\")\n    if err := desktopApp.Run(); err != nil {\n        fmt.Printf(\"Error: %v\\\\n\", err)\n    }\n}"),
			Note("info", "Build Tags",
				"The `//go:build !desktop` and `//go:build desktop` tags ensure only the correct entry point is compiled for each platform. The irgo CLI handles this automatically.",
			),
			H2("App Configuration"),
			P("The `app/` directory contains your router setup and application configuration:"),
			CodeFile("go", "app/app.go", "package app\n\nimport (\n    \"myapp/handlers\"\n    \"github.com/stukennedy/irgo/pkg/render\"\n    \"github.com/stukennedy/irgo/pkg/router\"\n)\n\nfunc NewRouter() *router.Router {\n    r := router.New()\n    renderer := render.NewTemplRenderer()\n\n    // Mount handlers\n    handlers.Mount(r, renderer)\n\n    return r\n}"),
			H2("Handlers"),
			P("The `handlers/` directory contains your HTTP handlers. Group related handlers into separate files:"),
			CodeFile("go", "handlers/handlers.go", "package handlers\n\nimport (\n    \"myapp/templates\"\n    \"github.com/stukennedy/irgo/pkg/render\"\n    \"github.com/stukennedy/irgo/pkg/router\"\n)\n\nvar renderer *render.TemplRenderer\n\nfunc Mount(r *router.Router, rend *render.TemplRenderer) {\n    renderer = rend\n\n    // Pages\n    r.GET(\"/\", HomePage)\n    r.GET(\"/about\", AboutPage)\n\n    // API routes\n    r.Route(\"/api\", func(r *router.Router) {\n        r.GET(\"/users\", ListUsers)\n        r.POST(\"/users\", CreateUser)\n    })\n}"),
			H2("Templates"),
			P("The `templates/` directory contains your templ templates. Organize by feature or page:"),
			Code("text", "templates/\n\u251c\u2500\u2500 layout.templ       # Base HTML structure\n\u251c\u2500\u2500 home.templ         # Home page\n\u251c\u2500\u2500 about.templ        # About page\n\u251c\u2500\u2500 components/\n\u2502   \u251c\u2500\u2500 nav.templ      # Navigation component\n\u2502   \u251c\u2500\u2500 footer.templ   # Footer component\n\u2502   \u2514\u2500\u2500 card.templ     # Reusable card component\n\u2514\u2500\u2500 users/\n    \u251c\u2500\u2500 list.templ     # User list page\n    \u251c\u2500\u2500 form.templ     # User form\n    \u2514\u2500\u2500 item.templ     # Single user item"),
			H2("Static Assets"),
			P("The `static/` directory serves static files like CSS, JavaScript, and images:"),
			Code("text", "static/\n\u251c\u2500\u2500 css/\n\u2502   \u251c\u2500\u2500 input.css      # Tailwind source file\n\u2502   \u2514\u2500\u2500 output.css     # Generated CSS (git-ignored)\n\u251c\u2500\u2500 js/\n\u2502   \u251c\u2500\u2500 datastar.js    # Datastar library (downloaded by irgo project new)\n\u2502   \u2514\u2500\u2500 app.js         # Custom JavaScript (if needed)\n\u2514\u2500\u2500 images/\n    \u2514\u2500\u2500 logo.png       # Static images"),
			Note("tip", "",
				"The `output.css` is generated by Tailwind during build. Add it to `.gitignore` and generate it as part of your build process.",
			),
			H2("Build Output"),
			P("Built artifacts are placed in the `build/` directory:"),
			Code("text", "build/\n\u251c\u2500\u2500 ios/\n\u2502   \u2514\u2500\u2500 Irgo.xcframework/    # iOS framework for Xcode\n\u251c\u2500\u2500 android/\n\u2502   \u2514\u2500\u2500 irgo.aar             # Android archive\n\u2514\u2500\u2500 desktop/\n    \u251c\u2500\u2500 macos/\n    \u2502   \u2514\u2500\u2500 MyApp.app/       # macOS application bundle\n    \u251c\u2500\u2500 windows/\n    \u2502   \u2514\u2500\u2500 MyApp.exe        # Windows executable\n    \u2514\u2500\u2500 linux/\n        \u2514\u2500\u2500 myapp            # Linux binary"),
			H2("Next Steps"),
			Bullets(
				"[Routing & Handlers](/docs/routing) - Deep dive into the router API",
				"[Templ Templates](/docs/templates) - Learn template syntax and patterns",
				"[Desktop Apps](/docs/desktop) - Desktop-specific configuration",
			),
		},
	},
	{
		Slug:  "routing",
		Title: "Routing",
		Blocks: []Block{
			P("irgo uses a chi-based router with a simplified API designed for Datastar applications. Handlers return HTML via SSE rather than writing directly to response writers."),
			H2("Basic Routing"),
			Code("go", "import \"github.com/stukennedy/irgo/pkg/router\"\n\nr := router.New()\n\n// Basic routes\nr.GET(\"/\", HomeHandler)\nr.POST(\"/users\", CreateUserHandler)\nr.PUT(\"/users/{id}\", UpdateUserHandler)\nr.DELETE(\"/users/{id}\", DeleteUserHandler)\nr.PATCH(\"/users/{id}\", PatchUserHandler)"),
			H2("Datastar SSE Handlers"),
			P("Datastar handlers return error and use ctx.SSE() to stream HTML updates via Server-Sent Events:"),
			Code("go", "// Page handlers return (string, error) for full page renders\nfunc HomeHandler(ctx *router.Context) (string, error) {\n    return renderer.Render(templates.HomePage())\n}\n\n// Datastar handlers return error and use SSE\nfunc UserHandler(ctx *router.Context) error {\n    id := ctx.Param(\"id\")\n    user, err := db.GetUser(id)\n    if err != nil {\n        // These write the response; they do not return an error.\n        ctx.NotFound(\"User not found\")\n        return nil\n    }\n    return ctx.SSE().PatchTempl(templates.UserProfile(user))\n}"),
			H2("URL Parameters"),
			P("Use curly braces for URL parameters:"),
			Code("go", "// Single parameter\nr.GET(\"/users/{id}\", func(ctx *router.Context) (string, error) {\n    id := ctx.Param(\"id\")\n    return fmt.Sprintf(\"User ID: %s\", id), nil\n})\n\n// Multiple parameters\nr.GET(\"/posts/{postID}/comments/{commentID}\", func(ctx *router.Context) (string, error) {\n    postID := ctx.Param(\"postID\")\n    commentID := ctx.Param(\"commentID\")\n    return fmt.Sprintf(\"Post %s, Comment %s\", postID, commentID), nil\n})"),
			H2("Query Parameters"),
			Code("go", "// GET /search?q=hello&limit=10\nr.GET(\"/search\", func(ctx *router.Context) (string, error) {\n    query := ctx.Query(\"q\")\n    limit := ctx.Query(\"limit\")\n\n    if query == \"\" {\n        ctx.BadRequest(\"Query parameter 'q' is required\")\n        return \"\", nil\n    }\n\n    results := search(query, limit)\n    return renderer.Render(templates.SearchResults(results))\n})"),
			H2("Form Data"),
			Code("go", "r.POST(\"/users\", func(ctx *router.Context) (string, error) {\n    name := ctx.FormValue(\"name\")\n    email := ctx.FormValue(\"email\")\n\n    if name == \"\" || email == \"\" {\n        ctx.BadRequest(\"Name and email are required\")\n        return \"\", nil\n    }\n\n    user := db.CreateUser(name, email)\n    return renderer.Render(templates.UserCard(user))\n})"),
			H2("Route Groups"),
			P("Organize related routes with groups:"),
			Code("go", "r.Route(\"/api\", func(r *router.Router) {\n    // All routes here are prefixed with /api\n    r.GET(\"/users\", ListUsers)\n    r.POST(\"/users\", CreateUser)\n\n    r.Route(\"/admin\", func(r *router.Router) {\n        // /api/admin/...\n        r.GET(\"/stats\", AdminStats)\n        r.POST(\"/reset\", AdminReset)\n    })\n})"),
			H2("Context API"),
			P("The router.Context provides methods for handling requests and responses:"),
			H3("Input Methods"),
			Code("go", "func handler(ctx *router.Context) (string, error) {\n    // URL parameters\n    id := ctx.Param(\"id\")\n\n    // Query string parameters\n    query := ctx.Query(\"q\")\n\n    // Form values\n    name := ctx.FormValue(\"name\")\n\n    // Request headers\n    token := ctx.Header(\"Authorization\")\n\n    // Access underlying request\n    req := ctx.Request\n\n    return \"\", nil\n}"),
			H3("Datastar Detection & Signals"),
			Code("go", "func handler(ctx *router.Context) error {\n    // Check if request is from Datastar\n    if ctx.IsDatastar() {\n        // Handle as SSE response\n        return ctx.SSE().PatchTempl(templates.UserCard(user))\n    }\n    // Return full page for non-Datastar requests\n    html, err := renderer.Render(templates.UserPage(user))\n    if err != nil {\n        return err\n    }\n    ctx.HTML(html)\n    return nil\n}\n\n// Read signals from Datastar request\nvar signals struct {\n    Name  string `json:\"name\"`\n    Email string `json:\"email\"`\n}\nctx.ReadSignals(&signals)"),
			H3("Response Methods"),
			Code("go", "// HTML responses\nctx.HTML(\"<div>Hello</div>\")\nctx.HTMLStatus(201, \"<div>Created</div>\")\n\n// JSON responses\nctx.JSON(user)\nctx.JSONStatus(201, user)\n\n// Redirects (Datastar-aware)\nctx.Redirect(\"/new-location\")\n\n// No content\nctx.NoContent()"),
			H3("Error Responses"),
			Code("go", "// Generic error\nctx.Error(err)\nctx.ErrorStatus(500, \"Internal error\")\n\n// Common HTTP errors\nctx.NotFound(\"Resource not found\")\nctx.BadRequest(\"Invalid input\")\n\n// There is no Unauthorized or Forbidden helper; use ErrorStatus.\nctx.ErrorStatus(http.StatusUnauthorized, \"Please log in\")\nctx.ErrorStatus(http.StatusForbidden, \"Access denied\")"),
			H3("SSE Response Methods"),
			P("Control Datastar behavior with SSE response methods:"),
			Code("go", "func handler(ctx *router.Context) error {\n    sse := ctx.SSE()\n\n    // Morph HTML into DOM (by element ID in the template)\n    sse.PatchTempl(templates.UserCard(user))\n\n    // Update client-side signals\n    sse.PatchSignals(map[string]any{\"name\": \"\", \"loading\": false})\n\n    // Remove elements from DOM\n    sse.Remove(\"#old-item\")\n\n    // Redirect to new URL\n    sse.Redirect(\"/users/123\")\n\n    // Log to browser console\n    sse.ConsoleLog(\"Update complete\")\n\n    return nil\n}"),
			Note("tip", "Multiple Updates",
				"With Datastar, you can call multiple `PatchTempl` methods in a single handler to update multiple elements. Each element is identified by its ID in the template.",
			),
			H2("Static Files"),
			Code("go", "// Serve static files from a directory\nr.Static(\"/static\", http.Dir(\"static\"))\n\n// Or use http.FileServer directly\nmux := http.NewServeMux()\nmux.Handle(\"/static/\", http.StripPrefix(\"/static/\",\n    http.FileServer(http.Dir(\"static\"))))\nmux.Handle(\"/\", r.Handler())"),
			H2("Middleware"),
			P("irgo includes common middleware:"),
			Code("go", "import \"github.com/stukennedy/irgo/pkg/router/middleware\"\n\nr := router.New()\n\n// Detect Datastar requests (sets ctx.IsDatastar())\nr.Use(middleware.DatastarRequestMiddleware)\n\n// Wrap non-Datastar responses in layout\nr.Use(middleware.LayoutWrapper(templates.Layout))\n\n// Prevent caching\nr.Use(middleware.NoCacheMiddleware)\n\n// CORS support\nr.Use(middleware.CORSMiddleware)\n\n// Require Datastar for routes\nr.Route(\"/api\", func(r *router.Router) {\n    r.Use(middleware.RequireDatastar)\n    r.DSGet(\"/user-card\", UserCardHandler)\n})"),
			H2("Getting the HTTP Handler"),
			P("Convert the router to a standard http.Handler:"),
			Code("go", "r := router.New()\n// ... register routes ...\n\n// Get the http.Handler\nhandler := r.Handler()\n\n// Use with http.ListenAndServe\nhttp.ListenAndServe(\":8080\", handler)\n\n// Or with desktop.New\napp := desktop.New(handler, config)"),
			H2("Next Steps"),
			Bullets(
				"[Templ Templates](/docs/templates) - Learn the templating syntax",
				"[Datastar Integration](/docs/datastar) - Datastar patterns and best practices",
				"[Testing](/docs/testing) - Test your handlers",
			),
		},
	},
	{
		Slug:  "templates",
		Title: "Templates",
		Blocks: []Block{
			P("irgo uses [templ](https://templ.guide) for type-safe HTML templating. Templ compiles to Go code, giving you compile-time error checking and full IDE support."),
			H2("Basic Syntax"),
			CodeFile("templ", "templates/greeting.templ", "package templates\n\n// Simple component\ntempl Greeting(name string) {\n    <div class=\"greeting\">\n        <h1>Hello, { name }!</h1>\n    </div>\n}"),
			P("After running `templ generate`, this creates `greeting_templ.go`."),
			H2("Rendering Templates"),
			Code("go", "import (\n    \"myapp/templates\"\n    \"github.com/stukennedy/irgo/pkg/render\"\n)\n\nrenderer := render.NewTemplRenderer()\n\nfunc handler(ctx *router.Context) (string, error) {\n    html, err := renderer.Render(templates.Greeting(\"World\"))\n    if err != nil {\n        return \"\", err\n    }\n    return html, nil\n}"),
			H2("Component Parameters"),
			Code("templ", "// Multiple parameters\ntempl UserCard(name string, email string, avatar string) {\n    <div class=\"user-card\">\n        <img src={ avatar } alt={ name } />\n        <h3>{ name }</h3>\n        <p>{ email }</p>\n    </div>\n}\n\n// Struct parameter\ntempl UserProfile(user User) {\n    <div class=\"profile\">\n        <h1>{ user.Name }</h1>\n        <p>{ user.Email }</p>\n        <span>Joined: { user.CreatedAt.Format(\"Jan 2, 2006\") }</span>\n    </div>\n}"),
			H2("Conditionals"),
			Code("templ", "templ Status(active bool) {\n    if active {\n        <span class=\"badge badge-success\">Active</span>\n    } else {\n        <span class=\"badge badge-danger\">Inactive</span>\n    }\n}\n\ntempl UserBadge(user User) {\n    <div class=\"badge\">\n        if user.IsAdmin {\n            <span class=\"admin\">Admin</span>\n        } else if user.IsModerator {\n            <span class=\"mod\">Moderator</span>\n        } else {\n            <span class=\"user\">Member</span>\n        }\n    </div>\n}"),
			H2("Loops"),
			Code("templ", "templ UserList(users []User) {\n    <ul class=\"user-list\">\n        for _, user := range users {\n            <li>\n                @UserCard(user.Name, user.Email, user.Avatar)\n            </li>\n        }\n    </ul>\n}\n\ntempl NumberedList(items []string) {\n    <ol>\n        for i, item := range items {\n            <li>{ fmt.Sprintf(\"%d. %s\", i+1, item) }</li>\n        }\n    </ol>\n}"),
			H2("Component Composition"),
			P("Use `@` to include other components:"),
			Code("templ", "templ Layout(title string) {\n    <!DOCTYPE html>\n    <html>\n        <head>\n            <title>{ title }</title>\n            <link rel=\"stylesheet\" href=\"/static/css/output.css\" />\n            <script type=\"module\" src=\"/static/js/datastar.js\"></script>\n        </head>\n        <body>\n            @Header()\n            <main>\n                { children... }\n            </main>\n            @Footer()\n        </body>\n    </html>\n}\n\ntempl Header() {\n    <header class=\"header\">\n        <a href=\"/\">Home</a>\n        <nav>\n            <a href=\"/about\">About</a>\n            <a href=\"/contact\">Contact</a>\n        </nav>\n    </header>\n}\n\ntempl Footer() {\n    <footer class=\"footer\">\n        <p>&copy; 2024 My App</p>\n    </footer>\n}"),
			H3("Using Layouts"),
			Code("templ", "templ HomePage() {\n    @Layout(\"Home\") {\n        <h1>Welcome!</h1>\n        <p>This is the home page.</p>\n    }\n}\n\ntempl AboutPage() {\n    @Layout(\"About\") {\n        <h1>About Us</h1>\n        <p>Learn more about us.</p>\n    }\n}"),
			Note("info", "",
				"The `{ children... }` syntax lets you pass content into a component. It's like React's `children` prop or Vue's slots.",
			),
			H2("Dynamic Attributes"),
			H3("Conditional Attributes"),
			Code("templ", "// Boolean attribute (checked, disabled, etc.)\ntempl Checkbox(checked bool) {\n    <input type=\"checkbox\" checked?={ checked } />\n}\n\n// Dynamic value\ntempl SelectedOption(value string, selected string) {\n    <option value={ value } selected?={ value == selected }>\n        { value }\n    </option>\n}"),
			H3("Conditional Classes"),
			Code("templ", "// Using templ.KV for conditional classes\ntempl TodoItem(todo Todo) {\n    <div class={ \"todo-item\", templ.KV(\"completed\", todo.Done) }>\n        <span class={ templ.KV(\"line-through\", todo.Done) }>\n            { todo.Title }\n        </span>\n    </div>\n}\n\n// Multiple conditional classes\ntempl Button(primary bool, large bool, disabled bool) {\n    <button class={\n        \"btn\",\n        templ.KV(\"btn-primary\", primary),\n        templ.KV(\"btn-lg\", large),\n        templ.KV(\"btn-disabled\", disabled),\n    } disabled?={ disabled }>\n        { children... }\n    </button>\n}"),
			H3("Safe URLs"),
			Code("templ", "// Use templ.SafeURL for dynamic URLs\ntempl Link(url string, text string) {\n    <a href={ templ.SafeURL(url) }>{ text }</a>\n}\n\n// For URLs you construct\ntempl UserLink(userID string) {\n    <a href={ templ.SafeURL(\"/users/\" + userID) }>\n        View Profile\n    </a>\n}"),
			H2("Datastar Patterns"),
			H3("Click to Load"),
			Code("templ", "templ LoadButton() {\n    <div data-signals=\"{loading: false}\">\n        <button\n            data-on:click=\"$loading = true; @get('/api/data')\"\n            data-attr:disabled=\"$loading\"\n        >\n            <span data-show=\"!$loading\">Load Data</span>\n            <span data-show=\"$loading\">Loading...</span>\n        </button>\n        <div id=\"result\"></div>\n    </div>\n}"),
			H3("Form Submission"),
			Code("templ", "templ TodoForm() {\n    <form\n        data-signals=\"{title: ''}\"\n        data-on:submit__prevent=\"@post('/todos')\"\n    >\n        <input\n            type=\"text\"\n            data-bind:title\n            placeholder=\"New todo...\"\n            required\n        />\n        <button type=\"submit\">Add</button>\n    </form>\n    <div id=\"todo-list\"></div>\n}"),
			H3("Delete with Confirmation"),
			Code("templ", "templ DeleteButton(id string) {\n    <div data-signals=\"{confirmDelete: false}\">\n        <button\n            data-show=\"!$confirmDelete\"\n            data-on:click=\"$confirmDelete = true\"\n            class=\"btn-danger\"\n        >\n            Delete\n        </button>\n        <div data-show=\"$confirmDelete\">\n            <span>Are you sure?</span>\n            <button data-on:click={ \"@delete('/items/\" + id + \"')\" }>Yes</button>\n            <button data-on:click=\"$confirmDelete = false\">No</button>\n        </div>\n    </div>\n}"),
			H3("Toggle/Update"),
			Code("templ", "templ TodoItem(todo Todo) {\n    <div id={ \"todo-\" + todo.ID } class=\"todo-item\">\n        <input\n            type=\"checkbox\"\n            checked?={ todo.Done }\n            data-on:click={ \"@patch('/todos/\" + todo.ID + \"')\" }\n        />\n        <span class={ templ.KV(\"line-through\", todo.Done) }>\n            { todo.Title }\n        </span>\n    </div>\n}"),
			H3("Infinite Scroll"),
			Code("templ", "templ ItemList(items []Item, page int, hasMore bool) {\n    for i, item := range items {\n        if i == len(items)-1 && hasMore {\n            // Last item triggers loading more\n            <div data-intersect={ fmt.Sprintf(\"@get('/items?page=%d')\", page+1) }>\n                @ItemCard(item)\n            </div>\n        } else {\n            @ItemCard(item)\n        }\n    }\n}"),
			H3("Multiple Updates"),
			Code("go", "// Update multiple elements with one SSE response\nfunc CreateItem(ctx *router.Context) error {\n    item := createItem()\n    count := getTotalCount()\n\n    sse := ctx.SSE()\n\n    // Update item list\n    sse.PatchTempl(templates.ItemCard(item))\n\n    // Update counter\n    sse.PatchTempl(templates.ItemCount(count))\n\n    // Clear input signal\n    sse.PatchSignals(map[string]any{\"title\": \"\"})\n\n    return nil\n}"),
			H2("Generating Templates"),
			Code("bash", "# Generate once\ntempl generate\n\n# Watch for changes\ntempl generate --watch\n\n# Or use the irgo CLI\nirgo project assets"),
			Note("tip", "",
				"When using `irgo server dev`, template generation is handled automatically via the air configuration.",
			),
			H2("Next Steps"),
			Bullets(
				"[Datastar Integration](/docs/datastar) - More Datastar patterns and techniques",
				"[Routing & Handlers](/docs/routing) - Connect templates to handlers",
				"[templ Documentation](https://templ.guide) - Full templ reference",
			),
		},
	},
	{
		Slug:  "datastar",
		Title: "Datastar",
		Blocks: []Block{
			P("Datastar is at the heart of irgo's interactivity model. It uses Server-Sent Events (SSE) and reactive signals to deliver real-time updates from your Go handlers to the browser."),
			H2("The Hypermedia Pattern"),
			P("The traditional SPA approach:"),
			Code("text", "User Click \u2192 JavaScript \u2192 API Call \u2192 JSON Response \u2192 JavaScript \u2192 DOM Update"),
			P("The Datastar/irgo approach:"),
			Code("text", "User Click \u2192 Datastar Request \u2192 Go Handler \u2192 SSE Stream \u2192 DOM Morph"),
			P("Your Go handlers use SSE to stream HTML updates. Datastar morphs them into the DOM. No client-side rendering, no state synchronization, no JavaScript frameworks."),
			H2("Core Datastar Attributes"),
			H3("Making Requests"),
			Code("html", "<!-- GET request -->\n<button data-on:click=\"@get('/api/users')\">Load Users</button>\n\n<!-- POST request -->\n<button data-on:click=\"@post('/api/users')\">Create User</button>\n\n<!-- PUT request -->\n<button data-on:click=\"@put('/api/users/123')\">Update</button>\n\n<!-- DELETE request -->\n<button data-on:click=\"@delete('/api/users/123')\">Delete</button>\n\n<!-- PATCH request -->\n<button data-on:click=\"@patch('/api/users/123')\">Patch</button>"),
			H3("Signals (Reactive State)"),
			P("Datastar uses signals for client-side reactive state. Define them with `data-signals`:"),
			Code("html", "<!-- Initialize signals -->\n<div data-signals=\"{name: '', count: 0, items: []}\">\n    <!-- Two-way binding -->\n    <input type=\"text\" data-bind:name placeholder=\"Enter name\" />\n\n    <!-- Display signal value -->\n    <span data-text=\"$name\"></span>\n\n    <!-- Use in expressions -->\n    <span data-text=\"'Count: ' + $count\"></span>\n</div>"),
			H3("Binding and Display"),
			Code("html", "<!-- Two-way input binding -->\n<input data-bind:email type=\"email\" />\n\n<!-- Checkbox binding -->\n<input type=\"checkbox\" data-bind:isActive />\n\n<!-- Display text -->\n<span data-text=\"$username\"></span>\n\n<!-- Conditional display -->\n<div data-show=\"$isLoggedIn\">Welcome back!</div>\n\n<!-- Dynamic classes -->\n<div data-class:active=\"$isSelected\">Item</div>\n<div data-class:hidden=\"!$visible\">Content</div>"),
			H3("Event Handling"),
			Code("html", "<!-- Click events -->\n<button data-on:click=\"@post('/api/action')\">Submit</button>\n\n<!-- With signal values (sent automatically) -->\n<button data-on:click=\"@post('/api/save')\">Save</button>\n\n<!-- Update signals on click -->\n<button data-on:click=\"$count++\">Increment</button>\n\n<!-- Keyboard events -->\n<input data-on:keyup=\"@get('/search')\" />\n\n<!-- With modifiers -->\n<input data-on:keyup__debounce.300ms=\"@get('/search')\" />\n<form data-on:submit__prevent=\"@post('/submit')\">\n\n<!-- Mouse events -->\n<div data-on:mousemove__throttle.100ms=\"@get('/track')\">\n    Track mouse\n</div>"),
			H3("Event Modifiers"),
			Code("html", "<!-- Debounce (wait for pause in events) -->\n<input data-on:keyup__debounce.300ms=\"@get('/search')\" />\n\n<!-- Throttle (limit event frequency) -->\n<div data-on:scroll__throttle.100ms=\"@get('/load-more')\">\n\n<!-- Prevent default -->\n<form data-on:submit__prevent=\"@post('/submit')\">\n\n<!-- Stop propagation -->\n<button data-on:click__stop=\"@delete('/item')\">\n\n<!-- Once (fire only once) -->\n<div data-on:click__once=\"@get('/init')\">\n\n<!-- Combine modifiers -->\n<input data-on:keyup__debounce.500ms__prevent=\"@get('/search')\" />"),
			H2("Go Handler Patterns"),
			H3("Basic SSE Response"),
			Code("go", "// Datastar handlers return error (not string, error)\nfunc CreateUser(ctx *router.Context) error {\n    var signals struct {\n        Name  string `json:\"name\"`\n        Email string `json:\"email\"`\n    }\n    ctx.ReadSignals(&signals)\n\n    user := createUser(signals.Name, signals.Email)\n\n    sse := ctx.SSE()\n    return sse.PatchTempl(templates.UserCard(user))\n}"),
			H3("Multiple Updates"),
			Code("go", "func ToggleTodo(ctx *router.Context) error {\n    id := ctx.Param(\"id\")\n    todo := toggleTodo(id)\n    count := getTodoCount()\n\n    sse := ctx.SSE()\n\n    // Update the todo item\n    sse.PatchTempl(templates.TodoItem(todo))\n\n    // Update the counter (different element)\n    sse.PatchTempl(templates.TodoCount(count))\n\n    return nil\n}"),
			H3("Updating Signals from Server"),
			Code("go", "func SubmitForm(ctx *router.Context) error {\n    var signals struct {\n        Title string `json:\"title\"`\n    }\n    ctx.ReadSignals(&signals)\n\n    // Process the form...\n    item := createItem(signals.Title)\n\n    sse := ctx.SSE()\n\n    // Add the new item to DOM\n    sse.PatchTempl(templates.ItemCard(item))\n\n    // Clear the input by updating the signal\n    sse.PatchSignals(map[string]any{\"title\": \"\"})\n\n    return nil\n}"),
			H3("Removing Elements"),
			Code("go", "func DeleteItem(ctx *router.Context) error {\n    id := ctx.Param(\"id\")\n    deleteItem(id)\n\n    sse := ctx.SSE()\n\n    // Remove the element from DOM\n    return sse.RemoveByID(\"item-\" + id)\n}"),
			H3("Redirects"),
			Code("go", "func CreateProject(ctx *router.Context) error {\n    var signals struct {\n        Name string `json:\"name\"`\n    }\n    ctx.ReadSignals(&signals)\n\n    project := createProject(signals.Name)\n\n    sse := ctx.SSE()\n    return sse.Redirect(\"/projects/\" + project.ID)\n}"),
			H2("Template Patterns"),
			H3("Basic Form"),
			Code("templ", "templ CreateForm() {\n    <form data-signals=\"{title: ''}\" data-on:submit__prevent=\"@post('/items')\">\n        <input\n            type=\"text\"\n            data-bind:title\n            placeholder=\"Enter title\"\n            required\n        />\n        <button type=\"submit\">Create</button>\n    </form>\n    <div id=\"items-list\"></div>\n}"),
			H3("Todo Item with Actions"),
			Code("templ", "templ TodoItem(todo Todo) {\n    <div id={ \"todo-\" + todo.ID } class=\"todo-item\">\n        <input\n            type=\"checkbox\"\n            checked?={ todo.Done }\n            data-on:click={ \"@patch('/todos/\" + todo.ID + \"')\" }\n        />\n        <span class={ templ.KV(\"completed\", todo.Done) }>\n            { todo.Title }\n        </span>\n        <button data-on:click={ \"@delete('/todos/\" + todo.ID + \"')\" }>\n            Delete\n        </button>\n    </div>\n}"),
			H3("Search with Debounce"),
			Code("templ", "templ SearchBox() {\n    <div data-signals=\"{query: ''}\">\n        <input\n            type=\"text\"\n            data-bind:query\n            data-on:keyup__debounce.300ms=\"@get('/search')\"\n            placeholder=\"Search...\"\n        />\n        <div id=\"search-results\"></div>\n    </div>\n}"),
			H3("Loading Indicator"),
			Code("templ", "templ LoadButton() {\n    <div data-signals=\"{loading: false}\">\n        <button\n            data-on:click=\"$loading = true; @get('/data').then(() => $loading = false)\"\n            data-attr:disabled=\"$loading\"\n        >\n            <span data-show=\"!$loading\">Load Data</span>\n            <span data-show=\"$loading\">Loading...</span>\n        </button>\n    </div>\n}"),
			Note("tip", "",
				"With Datastar, you can use signals for UI state (loading, modals, tabs) while keeping business data on the server. This hybrid approach gives you the best of both worlds.",
			),
			H2("Common Patterns"),
			H3("Modal Dialog"),
			Code("templ", "templ ModalTrigger() {\n    <div data-signals=\"{showModal: false}\">\n        <button data-on:click=\"$showModal = true\">\n            Open Modal\n        </button>\n\n        <div class=\"modal-backdrop\" data-show=\"$showModal\" data-on:click=\"$showModal = false\">\n            <div class=\"modal\" data-on:click__stop=\"\">\n                <h2>Confirm Action</h2>\n                <p>Are you sure?</p>\n                <button data-on:click=\"@post('/confirm'); $showModal = false\">\n                    Confirm\n                </button>\n                <button data-on:click=\"$showModal = false\">\n                    Cancel\n                </button>\n            </div>\n        </div>\n    </div>\n}"),
			H3("Tabs"),
			Code("templ", "templ Tabs() {\n    <div data-signals=\"{activeTab: 'overview'}\">\n        <nav class=\"tab-nav\">\n            <button\n                data-class:active=\"$activeTab === 'overview'\"\n                data-on:click=\"$activeTab = 'overview'; @get('/tabs/overview')\"\n            >\n                Overview\n            </button>\n            <button\n                data-class:active=\"$activeTab === 'settings'\"\n                data-on:click=\"$activeTab = 'settings'; @get('/tabs/settings')\"\n            >\n                Settings\n            </button>\n        </nav>\n        <div id=\"tab-content\">\n            <!-- Content loads here -->\n        </div>\n    </div>\n}"),
			H3("Infinite Scroll"),
			Code("templ", "templ FeedItem(item Item, isLast bool, nextPage int) {\n    if isLast {\n        <div\n            id={ \"item-\" + item.ID }\n            data-intersect={ fmt.Sprintf(\"@get('/feed?page=%d')\", nextPage) }\n        >\n            @ItemCard(item)\n        </div>\n    } else {\n        <div id={ \"item-\" + item.ID }>\n            @ItemCard(item)\n        </div>\n    }\n}"),
			H2("SSE Response Events"),
			P("The Datastar Go SDK provides these SSE response methods:"),
			Table(
				[]string{"Method", "Description"},
				[]string{"`PatchTempl(c)`", "Morph templ component into DOM"},
				[]string{"`PatchElements(id, html)`", "Morph raw HTML into element"},
				[]string{"`PatchSignals(map)`", "Update client-side signals"},
				[]string{"`RemoveElements(selector)`", "Remove elements from DOM"},
				[]string{"`Redirect(url)`", "Navigate to new URL"},
				[]string{"`Console(level, msg)`", "Log to browser console"},
			),
			H2("Initialization"),
			P("Use `data-init` to run code when an element is added to the DOM:"),
			Code("html", "<!-- Load data on page load -->\n<div data-init=\"@get('/api/initial-data')\">\n    Loading...\n</div>\n\n<!-- Initialize signals and fetch -->\n<div\n    data-signals=\"{items: []}\"\n    data-init=\"@get('/api/items')\"\n>\n    <div id=\"items-container\"></div>\n</div>"),
			H2("Next Steps"),
			Bullets(
				"[Templ Templates](/docs/templates) - Template syntax reference",
				"[Routing & Handlers](/docs/routing) - Handler patterns",
				"[Datastar Documentation](https://data-star.dev) - Full Datastar reference",
			),
		},
	},
	{
		Slug:  "realtime",
		Title: "Real-time updates",
		Blocks: []Block{
			P("irgo gives you two ways to push. Datastar's own transport is Server-Sent Events, which covers everything the client asks for; when the *server* needs to start the conversation, the framework ships a WebSocket hub."),
			H2("SSE with Datastar"),
			P("Datastar uses SSE natively for all interactions. Every Datastar request receives an SSE stream response, making real-time updates natural and simple."),
			Code("templ", "templ LiveDashboard() {\n    <div data-init=\"@get('/api/dashboard')\" data-signals=\"{stats: {}}\">\n        <div id=\"live-stats\">\n            Loading...\n        </div>\n    </div>\n}"),
			H2("Polling for Updates"),
			P("Use Datastar's interval modifier to poll for updates:"),
			Code("templ", "templ StatusIndicator() {\n    <div\n        data-init=\"@get('/api/status')\"\n        data-on:load__interval.5s=\"@get('/api/status')\"\n    >\n        <div id=\"status\">Checking...</div>\n    </div>\n}"),
			Code("go", "func GetStatus(ctx *router.Context) error {\n    status := checkSystemStatus()\n    return ctx.SSE().PatchTempl(templates.StatusBadge(status))\n}"),
			P("Polling is the right answer more often than it looks. It needs no connection to keep alive, it survives a sleeping phone, and at a five-second interval it costs one request per client per five seconds."),
			H2("Server Push"),
			P("When the server has to start the exchange — a notification, another user's message — polling is the wrong shape. The framework's hub is in `pkg/websocket`, and it holds the open connections:"),
			CodeFile("go", "app/app.go", Example("hub-setup")),
			P("Push from anywhere in your code — the hub is safe to call from any goroutine:"),
			Code("go", Example("hub-push")),
			Note("info", "",
				"The hub is reached differently per platform. On desktop, hand it to `desktop.NewWithHub(handler, hub, config)` and read it back with `app.Hub()`. On mobile the runtime owns one already — `mobile.GetHub()`, with `mobile.WebSocketBroadcast` and `mobile.WebSocketBroadcastAll` as shortcuts.",
			),
			H2("Chat Example"),
			P("The client half is ordinary Datastar. The form posts, and the messages arrive over the hub rather than in the response:"),
			CodeFile("templ", "templates/chat.templ", "templ ChatRoom(roomID string) {\n    <div\n        class=\"chat-room\"\n        data-signals=\"{message: ''}\"\n    >\n        <div id=\"messages\" class=\"messages\"></div>\n        <form data-on:submit__prevent={ \"@post('/chat/\" + roomID + \"/send')\" }>\n            <input\n                type=\"text\"\n                data-bind:message\n                placeholder=\"Type a message...\"\n            />\n            <button type=\"submit\">Send</button>\n        </form>\n    </div>\n}\n\ntempl ChatMessage(user string, message string, timestamp time.Time) {\n    <div class=\"message\">\n        <strong>{ user }</strong>\n        <span>{ message }</span>\n        <time>{ timestamp.Format(\"3:04 PM\") }</time>\n    </div>\n}"),
			CodeFile("go", "handlers/chat.go", Example("chat-send")),
			H2("Live Notifications"),
			Code("templ", "templ NotificationListener() {\n    <div data-signals=\"{unreadCount: 0}\">\n        <div id=\"notification-badge\" data-show=\"$unreadCount > 0\">\n            <span data-text=\"$unreadCount\"></span>\n        </div>\n        <div id=\"notification-list\"></div>\n    </div>\n}"),
			CodeFile("go", "notify.go", Example("notify")),
			H2("Next Steps"),
			Bullets(
				"[Datastar Integration](/docs/datastar) - Core Datastar patterns",
				"[API reference](/docs/api) - The hub's full surface, generated from the source",
				"[Examples](/docs/examples) - Complete examples",
			),
		},
	},
	{
		Slug:  "testing",
		Title: "Testing",
		Blocks: []Block{
			P("irgo provides testing utilities to help you test your handlers and templates."),
			H2("Test Client"),
			P("The testing package provides an HTTP client for testing handlers:"),
			Code("go", "import (\n    \"testing\"\n    irgotest \"github.com/stukennedy/irgo/pkg/testing\"\n)\n\nfunc TestListTodos(t *testing.T) {\n    r := app.NewRouter()\n    client := irgotest.NewClient(r.Handler())\n\n    resp := client.Get(\"/todos\")\n\n    resp.AssertOK(t)\n    resp.AssertContains(t, \"My Todos\")\n}"),
			H2("HTTP Methods"),
			Code("go", "client := irgotest.NewClient(handler)\n\n// GET request\nresp := client.Get(\"/users\")\n\n// GET with query parameters\nresp := client.Get(\"/search?q=hello\")\n\n// GET with a header — WithHeader returns a new client\nresp := client.WithHeader(\"Authorization\", \"Bearer ...\").Get(\"/users\")\n\n// POST with form data\nresp := client.PostForm(\"/users\", map[string]string{\n    \"name\":  \"John\",\n    \"email\": \"john@example.com\",\n})\n\n// POST with JSON — the body is a string, not a map\nresp := client.PostJSON(\"/api/users\", `{\"name\": \"John\"}`)\n\n// PUT and PATCH take a body; the Form and JSON variants take the data\nresp := client.PutForm(\"/users/123\", map[string]string{\"name\": \"Jane\"})\nresp := client.PatchJSON(\"/users/123\", `{\"name\": \"Jane\"}`)\n\n// DELETE request\nresp := client.Delete(\"/users/123\")"),
			H2("Assertions"),
			Code("go", "resp := client.Get(\"/users\")\n\n// Status assertions\nresp.AssertOK(t)                    // 200\nresp.AssertStatus(t, 201)           // Specific status\nresp.AssertRedirect(t)              // any 3xx\nresp.AssertNotFound(t)\nresp.AssertBadRequest(t)\n\n// Content assertions\nresp.AssertContains(t, \"Welcome\")\nresp.AssertNotContains(t, \"Error\")\nresp.AssertContainsAll(t, \"Welcome\", \"Sign out\")\n\n// Header assertions\nresp.AssertHeader(t, \"Content-Type\", \"text/html\")\nresp.AssertContentType(t, \"text/html\")\n\n// Get response data\nbody := resp.BodyString()     // string; resp.Body is the []byte\nstatus := resp.StatusCode     // int"),
			H2("Testing Datastar SSE Requests"),
			Code("go", "func TestDatastarRequest(t *testing.T) {\n    client := irgotest.NewClient(handler)\n\n    // Simulate a Datastar request\n    resp := client.Datastar().Get(\"/users\")\n\n    resp.AssertOK(t)\n    resp.AssertSSE(t)\n\n    // Check for the patch event, and what it carried\n    resp.AssertSSEEvent(t, \"datastar-patch-elements\")\n    resp.AssertSSEContains(t, \"<div id=\\\"user-list\\\">\")\n}\n\nfunc TestDatastarSignals(t *testing.T) {\n    client := irgotest.NewClient(handler)\n\n    // Send signals up with the request\n    resp := client.Datastar().PostJSON(\"/counter/increment\", `{\"count\": 41}`)\n\n    resp.AssertOK(t)\n    resp.AssertSSEContains(t, \"42\")\n}"),
			H3("Building a Request"),
			P("`RequestBuilder` composes a request when the client's shortcuts do not fit:"),
			Code("go", "func TestCreateUser(t *testing.T) {\n    resp := irgotest.NewRequest(\"POST\", \"/users\").\n        WithFormBody(map[string]string{\n            \"name\":  \"John\",\n            \"email\": \"john@example.com\",\n        }).\n        AsDatastar().\n        Execute(app.NewRouter().Handler())\n\n    resp.AssertOK(t)\n    resp.AssertContains(t, \"John\")\n}"),
			H2("Testing Templates"),
			Code("go", "func TestUserCard(t *testing.T) {\n    user := User{\n        ID:    \"123\",\n        Name:  \"John\",\n        Email: \"john@example.com\",\n    }\n\n    renderer := render.NewTemplRenderer()\n    html, err := renderer.Render(templates.UserCard(user))\n\n    if err != nil {\n        t.Fatalf(\"render error: %v\", err)\n    }\n\n    if !strings.Contains(html, \"John\") {\n        t.Error(\"expected card to contain user name\")\n    }\n\n    if !strings.Contains(html, \"john@example.com\") {\n        t.Error(\"expected card to contain email\")\n    }\n}"),
			H2("Running Tests"),
			Code("bash", "# Run all tests\ngo test ./...\n\n# Run with verbose output\ngo test -v ./...\n\n# Run specific package\ngo test ./handlers/...\n\n# Run with coverage\ngo test -cover ./..."),
			H2("Example Test File"),
			CodeFile("go", "handlers/todos_test.go", "package handlers\n\nimport (\n    \"testing\"\n    \"myapp/app\"\n    irgotest \"github.com/stukennedy/irgo/pkg/testing\"\n)\n\nfunc TestTodoWorkflow(t *testing.T) {\n    r := app.NewRouter()\n    client := irgotest.NewClient(r.Handler())\n\n    // List todos (empty)\n    resp := client.Get(\"/todos\")\n    resp.AssertOK(t)\n    resp.AssertContains(t, \"No todos yet\")\n\n    // Create todo\n    resp = client.PostForm(\"/todos\", map[string]string{\n        \"title\": \"Buy groceries\",\n    })\n    resp.AssertOK(t)\n    resp.AssertContains(t, \"Buy groceries\")\n\n    // Toggle todo\n    resp = client.PostForm(\"/todos/1/toggle\", nil)\n    resp.AssertOK(t)\n    resp.AssertContains(t, \"completed\")\n\n    // Delete todo\n    resp = client.Delete(\"/todos/1\")\n    resp.AssertOK(t)\n}"),
			H2("Next Steps"),
			Bullets(
				"[Routing & Handlers](/docs/routing) - Handler API reference",
				"[Templ Templates](/docs/templates) - Template testing",
			),
		},
	},
	{
		Slug:  "web",
		Title: "Web",
		Blocks: []Block{
			P("irgo apps work as standard web applications out of the box. The web mode is primarily used for development, but can also be deployed as a traditional web server."),
			H2("Development Server"),
			Code("bash", "irgo server dev"),
			P("This starts a web server at http://localhost:8080 with hot reload. Changes to Go and templ files are automatically detected and the server restarts."),
			H2("How It Works"),
			P("In web mode, irgo runs as a standard Go HTTP server. The same handlers and templates you write for mobile and desktop work identically in the browser."),
			Code("go", "// main.go (web/mobile entry point)\n//go:build !desktop\n\nfunc runDevServer() {\n    r := app.NewRouter()\n\n    mux := http.NewServeMux()\n    mux.Handle(\"/static/\", http.StripPrefix(\"/static/\",\n        http.FileServer(http.Dir(\"static\"))))\n    mux.Handle(\"/\", r.Handler())\n\n    fmt.Println(\"Dev server at http://localhost:8080\")\n    log.Fatal(http.ListenAndServe(\":8080\", mux))\n}"),
			H2("Hot Reload Configuration"),
			P("Hot reload is powered by [air](https://github.com/air-verse/air). The configuration is in `.air.toml`:"),
			Code("toml", "[build]\ncmd = \"templ generate && npx tailwindcss -i ./static/css/input.css -o ./static/css/output.css --minify && go build -o ./tmp/main .\"\nbin = \"tmp/main serve\"\ninclude_ext = [\"go\", \"templ\", \"html\", \"css\"]\nexclude_dir = [\"tmp\", \"vendor\", \"node_modules\"]\n\n[misc]\nclean_on_exit = true"),
			P("This configuration runs templ generation and Tailwind CSS compilation on every file change, so you don't need separate watchers."),
			H2("Production Deployment"),
			P("For production web deployment, build a standard Go binary:"),
			Code("bash", "# Generate templates\ntempl generate\n\n# Build CSS\nnpx tailwindcss -i static/css/input.css -o static/css/output.css --minify\n\n# Build binary\ngo build -o myapp .\n\n# Run\n./myapp serve"),
			H2("Docker Deployment"),
			Code("dockerfile", "FROM golang:1.21-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN go install github.com/a-h/templ/cmd/templ@latest\nRUN templ generate\nRUN CGO_ENABLED=0 go build -o myapp .\n\nFROM alpine:latest\nWORKDIR /app\nCOPY --from=builder /app/myapp .\nCOPY --from=builder /app/static ./static\nEXPOSE 8080\nCMD [\"./myapp\", \"serve\"]"),
			H2("Next Steps"),
			Bullets(
				"[Desktop Apps](/docs/desktop) - Package as desktop application",
				"[Mobile Apps](/docs/mobile) - Build for iOS and Android",
				"[Deployment](/docs/deployment) - Deployment strategies",
			),
		},
	},
	{
		Slug:  "desktop",
		Title: "Desktop",
		Blocks: []Block{
			P("irgo's desktop mode creates native applications for macOS, Windows, and Linux using a real HTTP server and native webview window."),
			H2("How Desktop Mode Works"),
			P("Unlike mobile mode (which uses virtual HTTP), desktop mode:"),
			Steps(
				"Starts a Go HTTP server on an auto-selected localhost port",
				"Opens a native window with an embedded browser engine (WebKit on macOS, Chromium on Windows/Linux)",
				"The webview navigates to the localhost URL",
			),
			Code("text", "\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510\n\u2502           Desktop App                    \u2502\n\u2502  \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u2502\n\u2502  \u2502    Native Webview Window         \u2502    \u2502\n\u2502  \u2502  (Chromium/WebKit)               \u2502    \u2502\n\u2502  \u2502  Navigates to localhost:PORT     \u2502    \u2502\n\u2502  \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2502\n\u2502                 \u2502 HTTP                   \u2502\n\u2502  \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u25bc\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u2502\n\u2502  \u2502    Go HTTP Server                \u2502    \u2502\n\u2502  \u2502  \u2022 Page Routes \u2192 HTML            \u2502    \u2502\n\u2502  \u2502  \u2022 API Routes \u2192 JSON             \u2502    \u2502\n\u2502  \u2502  \u2022 Static Assets                 \u2502    \u2502\n\u2502  \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2502\n\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518"),
			P("This architecture means your app works exactly like the web dev server, but packaged as a native desktop application."),
			H2("Prerequisites"),
			P("Desktop builds require CGO and a C compiler:"),
			Bullets(
				"**macOS:** Xcode Command Line Tools (`xcode-select --install`)",
				"**Windows:** MinGW-w64 or similar",
				"**Linux:** GCC and WebKit2GTK (`apt install build-essential libwebkit2gtk-4.0-dev`)",
			),
			Note("warning", "",
				"CGO must be enabled. If you see errors about CGO_ENABLED=0, ensure you have a C compiler installed and set `CGO_ENABLED=1`.",
			),
			H2("Desktop Entry Point"),
			P("Desktop apps use a separate entry point with the `desktop` build tag:"),
			CodeFile("go", "main_desktop.go", "//go:build desktop\n\npackage main\n\nimport (\n    \"flag\"\n    \"fmt\"\n    \"net/http\"\n\n    \"myapp/app\"\n    \"github.com/stukennedy/irgo/desktop\"\n)\n\nfunc main() {\n    devMode := flag.Bool(\"dev\", false, \"Enable devtools\")\n    flag.Parse()\n\n    // Create router\n    r := app.NewRouter()\n\n    // Set up HTTP handler with static files\n    mux := http.NewServeMux()\n    staticDir := desktop.FindStaticDir()\n    mux.Handle(\"/static/\", http.StripPrefix(\"/static/\",\n        http.FileServer(http.Dir(staticDir))))\n    mux.Handle(\"/\", r.Handler())\n\n    // Configure desktop app\n    config := desktop.DefaultConfig()\n    config.Title = \"My App\"\n    config.Debug = *devMode\n\n    // Create and run\n    desktopApp := desktop.New(mux, config)\n\n    fmt.Println(\"Starting desktop app...\")\n    if err := desktopApp.Run(); err != nil {\n        fmt.Printf(\"Error: %v\\\\n\", err)\n    }\n}"),
			H2("Configuration"),
			Code("go", "config := desktop.Config{\n    Title:     \"My App\",     // Window title\n    Width:     1024,         // Initial window width\n    Height:    768,          // Initial window height\n    Resizable: true,         // Allow window resizing\n    Debug:     false,        // Enable browser devtools\n    Port:      0,            // 0 = auto-select available port\n}\n\n// Or start with defaults\nconfig := desktop.DefaultConfig()\nconfig.Title = \"My App\"\nconfig.Debug = true"),
			H3("Configuration Options"),
			Table(
				[]string{"Option", "Type", "Default", "Description"},
				[]string{"`Title`", "string", "\"Irgo App\"", "Window title bar text"},
				[]string{"`Width`", "int", "1024", "Initial window width in pixels"},
				[]string{"`Height`", "int", "768", "Initial window height in pixels"},
				[]string{"`Resizable`", "bool", "true", "Allow window resizing"},
				[]string{"`Debug`", "bool", "false", "Enable browser devtools (right-click inspect)"},
				[]string{"`Port`", "int", "0", "Server port (0 = auto-select)"},
			),
			H2("Running Desktop Apps"),
			Code("bash", "# Run directly (compiles and runs)\nirgo app run desktop\n\n# With devtools enabled (for debugging)\nirgo app run desktop --dev"),
			H2("Building Desktop Apps"),
			Code("bash", "# Build for current platform\nirgo app build desktop\n\n# Build for specific platform\nirgo app build desktop macos     # Creates build/desktop/macos/MyApp.app\nirgo app build desktop windows   # Creates build/desktop/windows/MyApp.exe\nirgo app build desktop linux     # Creates build/desktop/linux/myapp"),
			H3("Build Output"),
			Code("text", "build/desktop/\n\u251c\u2500\u2500 macos/\n\u2502   \u2514\u2500\u2500 MyApp.app/           # macOS application bundle\n\u2502       \u2514\u2500\u2500 Contents/\n\u2502           \u251c\u2500\u2500 MacOS/\n\u2502           \u2502   \u2514\u2500\u2500 myapp    # Executable\n\u2502           \u251c\u2500\u2500 Resources/\n\u2502           \u2502   \u2514\u2500\u2500 static/  # Static assets\n\u2502           \u2514\u2500\u2500 Info.plist   # App metadata\n\u251c\u2500\u2500 windows/\n\u2502   \u2514\u2500\u2500 MyApp.exe            # Windows executable\n\u2514\u2500\u2500 linux/\n    \u2514\u2500\u2500 myapp                # Linux binary"),
			H2("Utility Functions"),
			Code("go", "import \"github.com/stukennedy/irgo/desktop\"\n\n// Find static files directory\n// Works both in dev (./static) and bundled app\nstaticDir := desktop.FindStaticDir()\n\n// Find bundled resources\n// Looks in app bundle on macOS, same dir as exe on Windows/Linux\nresourcePath := desktop.FindResourcePath(\"config.json\")"),
			H2("Desktop vs Mobile Comparison"),
			Table(
				[]string{"Aspect", "Desktop", "Mobile"},
				[]string{"HTTP", "Real localhost server", "Virtual (no sockets)"},
				[]string{"Bridge", "None (direct HTTP)", "gomobile + native code"},
				[]string{"Entry Point", "`main_desktop.go`", "`main.go`"},
				[]string{"Build Tag", "`desktop`", "`!desktop`"},
				[]string{"CGO Required", "Yes (webview)", "No"},
				[]string{"DevTools", "Native browser devtools", "Safari/Chrome remote debugging"},
			),
			H2("Troubleshooting"),
			H3("CGO Errors"),
			P("If you see \"CGO_ENABLED=0\" errors:"),
			Code("bash", "# Check CGO is enabled\ngo env CGO_ENABLED\n\n# Set it if needed\nexport CGO_ENABLED=1\n\n# Make sure you have a C compiler\n# macOS\nxcode-select --install\n\n# Linux\nsudo apt install build-essential"),
			H3("Webview Not Showing (Linux)"),
			Code("bash", "# Install WebKit2GTK\nsudo apt install libwebkit2gtk-4.0-dev"),
			H3("Static Files Not Found"),
			P("Use `desktop.FindStaticDir()` to locate static files. It handles both development and bundled app scenarios."),
			H2("Next Steps"),
			Bullets(
				"[Mobile Apps](/docs/mobile) - iOS and Android development",
				"[Deployment](/docs/deployment) - Packaging and distribution",
				"[Examples](/docs/examples) - Sample desktop applications",
			),
		},
	},
	{
		Slug:  "mobile",
		Title: "Mobile",
		Blocks: []Block{
			P("irgo enables you to build native iOS and Android apps using Go, HTML, and Datastar. The mobile architecture uses a \"virtual HTTP\" approach where requests are handled in-process without network sockets."),
			H2("How Mobile Mode Works"),
			Code("text", "\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510\n\u2502            Mobile App                    \u2502\n\u2502  \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u2502\n\u2502  \u2502     WebView (Datastar)            \u2502    \u2502\n\u2502  \u2502  \u2022 HTML rendered by Go templates \u2502    \u2502\n\u2502  \u2502  \u2022 Requests via irgo:// scheme   \u2502    \u2502\n\u2502  \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2502\n\u2502                 \u2502                        \u2502\n\u2502  \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u25bc\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u2502\n\u2502  \u2502   Native Bridge (Swift/Kotlin)   \u2502    \u2502\n\u2502  \u2502  \u2022 Intercepts irgo:// requests   \u2502    \u2502\n\u2502  \u2502  \u2022 Routes to Go via gomobile     \u2502    \u2502\n\u2502  \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2502\n\u2502                 \u2502                        \u2502\n\u2502  \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u25bc\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u2502\n\u2502  \u2502     Go Runtime (gomobile bind)   \u2502    \u2502\n\u2502  \u2502  \u2022 HTTP router (chi)             \u2502    \u2502\n\u2502  \u2502  \u2022 Template rendering (templ)    \u2502    \u2502\n\u2502  \u2502  \u2022 Business logic                \u2502    \u2502\n\u2502  \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2502\n\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518"),
			P("Key characteristics:"),
			Bullets(
				"**No network sockets** - Requests never leave the device",
				"**In-process execution** - Go handlers run directly in the app process",
				"**Custom URL scheme** - Datastar uses `irgo://` for requests",
				"**gomobile binding** - Go code compiled to native frameworks",
			),
			H2("Prerequisites"),
			H3("Common Requirements"),
			Bullets(
				"Go",
				"iOS: Xcode — the one thing irgo cannot install for you",
				"Android: nothing. `irgo app build android` fetches the JDK, SDK and NDK itself",
			),
			H3("iOS Development"),
			Bullets(
				"macOS with Xcode installed",
				"iOS Simulator or physical device",
				"Apple Developer account (for device deployment)",
			),
			H3("Android Development"),
			Bullets(
				"Android Studio with SDK installed",
				"Android NDK (install via SDK Manager)",
				"Android Emulator or physical device",
			),
			H2("Mobile Entry Point"),
			P("The mobile entry point uses the `!desktop` build tag:"),
			CodeFile("go", "main.go", "//go:build !desktop\n\npackage main\n\nimport (\n    \"fmt\"\n    \"log\"\n    \"net/http\"\n    \"os\"\n\n    \"myapp/app\"\n    \"github.com/stukennedy/irgo/mobile\"\n)\n\nfunc main() {\n    // If run with \"serve\" argument, start web dev server\n    if len(os.Args) > 1 && os.Args[1] == \"serve\" {\n        runDevServer()\n        return\n    }\n    // Otherwise, initialize for mobile\n    initMobile()\n}\n\nfunc initMobile() {\n    mobile.Initialize()\n    r := app.NewRouter()\n    mobile.SetHandler(r.Handler())\n    fmt.Println(\"Mobile app initialized\")\n}\n\nfunc runDevServer() {\n    r := app.NewRouter()\n    mux := http.NewServeMux()\n    mux.Handle(\"/static/\", http.StripPrefix(\"/static/\",\n        http.FileServer(http.Dir(\"static\"))))\n    mux.Handle(\"/\", r.Handler())\n\n    fmt.Println(\"Dev server at http://localhost:8080\")\n    log.Fatal(http.ListenAndServe(\":8080\", mux))\n}"),
			H2("iOS Development"),
			H3("Development with Hot Reload"),
			Code("bash", "# Start iOS Simulator with hot reload\nirgo app run ios --dev"),
			P("This watches for changes in your Go and templ files, rebuilds the framework, and refreshes the Simulator automatically."),
			H3("Production Build"),
			Code("bash", "# Build iOS framework\nirgo app build ios\n\n# Build and run on Simulator\nirgo app run ios"),
			H3("Build Output"),
			Code("text", "build/ios/\n\u2514\u2500\u2500 Irgo.xcframework/\n    \u251c\u2500\u2500 ios-arm64/\n    \u2502   \u2514\u2500\u2500 Irgo.framework/     # Device framework\n    \u2514\u2500\u2500 ios-arm64_x86_64-simulator/\n        \u2514\u2500\u2500 Irgo.framework/     # Simulator framework"),
			H3("Xcode Integration"),
			Steps(
				"Open your Xcode project in `ios/`",
				"Drag `Irgo.xcframework` into your project",
				"Ensure \"Embed & Sign\" is selected in Frameworks settings",
				"Build and run from Xcode",
			),
			H2("Android Development"),
			H3("Development with Hot Reload"),
			Code("bash", "# Start Android Emulator with hot reload\nirgo app run android --dev"),
			H3("Production Build"),
			Code("bash", "# Build Android AAR\nirgo app build android\n\n# Build and run on Emulator\nirgo app run android"),
			H3("Build Output"),
			Code("text", "build/android/\n\u2514\u2500\u2500 irgo.aar                    # Android Archive"),
			H3("Android Studio Integration"),
			Steps(
				"Open your Android project in `android/`",
				"Copy `irgo.aar` to `app/libs/`",
				"Add to `build.gradle`: `implementation files('libs/irgo.aar')`",
				"Build and run from Android Studio",
			),
			H2("The Virtual HTTP Adapter"),
			P("The mobile bridge uses an HTTP adapter that executes handlers in memory:"),
			Code("go", "// The adapter converts core.Request/Response to net/http\n// This happens automatically when you call mobile.SetHandler()\n\nimport \"github.com/stukennedy/irgo/pkg/adapter\"\n\n// The adapter executes handlers without network I/O\nadapter := adapter.NewHTTPAdapter(handler)\n\n// Native code calls this with request data\nresponse := adapter.HandleRequest(request)"),
			Note("info", "",
				"The adapter uses special `core.Request` and `core.Response` types that are compatible with gomobile (which doesn't support maps or slices of custom types).",
			),
			H2("Static Assets on Mobile"),
			P("Static files are bundled into the native app and served via the Go runtime:"),
			Code("go", "// In your router setup\nr := router.New()\n\n// Embed static files\n//go:embed static\nvar staticFS embed.FS\n\n// Serve embedded files\nr.Static(\"/static\", http.FS(staticFS))"),
			H2("Debugging Mobile Apps"),
			H3("iOS Debugging"),
			Steps(
				"Open Safari and go to Develop menu",
				"Select your Simulator or device",
				"Choose your app's WebView",
				"Use Safari Web Inspector to debug",
			),
			H3("Android Debugging"),
			Steps(
				"Open Chrome and go to `chrome://inspect`",
				"Your app's WebView should appear under \"Remote Target\"",
				"Click \"inspect\" to open DevTools",
			),
			Note("tip", "",
				"Enable WebView debugging in your native code for production builds if needed. For security, disable it in release builds.",
			),
			H2("Mobile vs Desktop Comparison"),
			Table(
				[]string{"Aspect", "Mobile", "Desktop"},
				[]string{"HTTP", "Virtual (no sockets)", "Real localhost server"},
				[]string{"Bridge", "gomobile + native code", "None (direct HTTP)"},
				[]string{"Entry Point", "`main.go`", "`main_desktop.go`"},
				[]string{"Build Tag", "`!desktop`", "`desktop`"},
				[]string{"CGO Required", "No", "Yes (webview)"},
				[]string{"Build Tool", "gomobile bind", "go build"},
			),
			H2("Troubleshooting"),
			H3("gomobile not found"),
			Code("bash", "go install golang.org/x/mobile/cmd/gomobile@latest\ngomobile init"),
			H3("Android NDK not found"),
			P("Install via Android Studio SDK Manager, or set:"),
			Code("bash", "export ANDROID_HOME=$HOME/Library/Android/sdk\nexport ANDROID_NDK_HOME=$ANDROID_HOME/ndk/<version>"),
			H3("iOS build fails"),
			P("Ensure Xcode CLI tools are installed and selected:"),
			Code("bash", "xcode-select --install\nsudo xcode-select -s /Applications/Xcode.app/Contents/Developer"),
			H2("Next Steps"),
			Bullets(
				"[Desktop Apps](/docs/desktop) - Desktop development",
				"[Deployment](/docs/deployment) - App store distribution",
				"[Examples](/docs/examples) - Sample mobile applications",
			),
		},
	},
	{
		Slug:  "deployment",
		Title: "Deployment",
		Blocks: []Block{
			P("This guide covers deploying irgo apps to various platforms: desktop distribution, mobile app stores, and web hosting."),
			H2("Desktop Distribution"),
			H3("macOS"),
			Code("bash", "# Build macOS app bundle\nirgo app build desktop macos"),
			P("This creates a `.app` bundle in `build/desktop/macos/`."),
			P("For distribution:"),
			Steps(
				"Sign the app with your Apple Developer certificate",
				"Notarize the app with Apple",
				"Create a DMG for distribution",
			),
			Code("bash", "# Sign the app\ncodesign --deep --force --sign \"Developer ID Application: Your Name\" MyApp.app\n\n# Create DMG\nhdiutil create -volname \"MyApp\" -srcfolder MyApp.app -ov -format UDZO MyApp.dmg\n\n# Notarize\nxcrun notarytool submit MyApp.dmg --apple-id you@email.com --team-id TEAMID --password @keychain:AC_PASSWORD"),
			H3("Windows"),
			Code("bash", "# Build Windows executable\nirgo app build desktop windows"),
			P("Creates `.exe` in `build/desktop/windows/`."),
			P("For distribution, consider:"),
			Bullets(
				"Code signing with a certificate",
				"Creating an installer (NSIS, WiX, Inno Setup)",
				"Including Visual C++ redistributables if needed",
			),
			H3("Linux"),
			Code("bash", "# Build Linux binary\nirgo app build desktop linux"),
			P("Distribution options:"),
			Bullets(
				"AppImage for universal distribution",
				"Flatpak for sandboxed distribution",
				"DEB/RPM packages for specific distributions",
			),
			H2("Mobile App Stores"),
			H3("iOS App Store"),
			Steps(
				"Build the iOS framework: `irgo app build ios`",
				"Open the Xcode project in `ios/`",
				"Add the framework to your project",
				"Configure signing with your Apple Developer account",
				"Archive and upload to App Store Connect",
			),
			Note("info", "",
				"Ensure your app meets Apple's App Store Review Guidelines. Apps using WebViews must provide significant native functionality.",
			),
			H3("Google Play Store"),
			Steps(
				"Build the Android AAR: `irgo app build android`",
				"Or open `android/Example` in Android Studio, if you prefer its UI",
				"Add the AAR to your project",
				"Configure signing with your keystore",
				"Generate signed APK or App Bundle",
				"Upload to Google Play Console",
			),
			Code("bash", "# Generate signed bundle\n./gradlew bundleRelease"),
			H2("Web Deployment"),
			H3("Docker"),
			CodeFile("dockerfile", "Dockerfile", "FROM golang:1.21-alpine AS builder\n\nWORKDIR /app\n\n# Install templ\nRUN go install github.com/a-h/templ/cmd/templ@latest\n\n# Copy and build\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN templ generate\nRUN CGO_ENABLED=0 go build -o server .\n\n# Runtime image\nFROM alpine:latest\nWORKDIR /app\nCOPY --from=builder /app/server .\nCOPY --from=builder /app/static ./static\n\nEXPOSE 8080\nCMD [\"./server\", \"serve\"]"),
			Code("bash", "# Build and run\ndocker build -t myapp .\ndocker run -p 8080:8080 myapp"),
			H3("Fly.io"),
			CodeFile("toml", "fly.toml", "app = \"myapp\"\nprimary_region = \"ord\"\n\n[build]\n  dockerfile = \"Dockerfile\"\n\n[http_service]\n  internal_port = 8080\n  force_https = true\n\n[[services]]\n  internal_port = 8080\n  protocol = \"tcp\"\n\n  [[services.ports]]\n    port = 80\n    handlers = [\"http\"]\n\n  [[services.ports]]\n    port = 443\n    handlers = [\"tls\", \"http\"]"),
			Code("bash", "fly launch\nfly deploy"),
			H3("Railway"),
			P("Railway auto-detects Go apps. Just connect your repository and deploy."),
			Code("bash", "# Set start command in Railway dashboard or railway.json\n{\n  \"build\": {\n    \"builder\": \"DOCKERFILE\"\n  },\n  \"deploy\": {\n    \"startCommand\": \"./server serve\"\n  }\n}"),
			H3("Traditional VPS"),
			Code("bash", "# Build locally\nGOOS=linux GOARCH=amd64 go build -o myapp .\n\n# Upload to server\nscp myapp user@server:/opt/myapp/\nscp -r static user@server:/opt/myapp/\n\n# On server: create systemd service\ncat > /etc/systemd/system/myapp.service << EOF\n[Unit]\nDescription=MyApp\nAfter=network.target\n\n[Service]\nType=simple\nUser=www-data\nWorkingDirectory=/opt/myapp\nExecStart=/opt/myapp/myapp serve\nRestart=always\n\n[Install]\nWantedBy=multi-user.target\nEOF\n\n# Enable and start\nsystemctl enable myapp\nsystemctl start myapp"),
			H2("Environment Configuration"),
			Code("go", "// Use environment variables for configuration\nport := os.Getenv(\"PORT\")\nif port == \"\" {\n    port = \"8080\"\n}\n\ndbURL := os.Getenv(\"DATABASE_URL\")\napiKey := os.Getenv(\"API_KEY\")"),
			H2("Next Steps"),
			Bullets(
				"[Desktop Apps](/docs/desktop) - Desktop-specific options",
				"[Mobile Apps](/docs/mobile) - Mobile-specific options",
				"[Examples](/docs/examples) - Deployment examples",
			),
		},
	},
	{
		Slug:  "examples",
		Title: "Examples",
		Blocks: []Block{
			P("Learn irgo through complete, working examples. Each example demonstrates key patterns and can be used as a starting point for your own apps."),
			H2("Todo App"),
			P("The classic todo app demonstrates CRUD operations, form handling, and Datastar interactions."),
			H3("Handler"),
			CodeFile("go", "handlers/todos.go", "package handlers\n\nimport (\n    \"fmt\"\n    \"myapp/templates\"\n    \"github.com/stukennedy/irgo/pkg/router\"\n)\n\ntype Todo struct {\n    ID    string\n    Title string\n    Done  bool\n}\n\nvar todos = []Todo{}\nvar nextID = 1\n\nfunc ListTodos(ctx *router.Context) error {\n    return ctx.SSE().PatchTempl(templates.TodoList(todos))\n}\n\nfunc CreateTodo(ctx *router.Context) error {\n    var signals struct {\n        Title string `json:\"title\"`\n    }\n    ctx.ReadSignals(&signals)\n\n    if signals.Title == \"\" {\n        ctx.BadRequest(\"Title is required\")\n        return nil\n    }\n\n    todo := Todo{\n        ID:    fmt.Sprintf(\"%d\", nextID),\n        Title: signals.Title,\n        Done:  false,\n    }\n    nextID++\n    todos = append(todos, todo)\n\n    sse := ctx.SSE()\n    sse.PatchTempl(templates.TodoItem(todo))\n    sse.PatchSignals(map[string]any{\"title\": \"\"}) // Clear input\n    return nil\n}\n\nfunc ToggleTodo(ctx *router.Context) error {\n    id := ctx.Param(\"id\")\n    for i := range todos {\n        if todos[i].ID == id {\n            todos[i].Done = !todos[i].Done\n            return ctx.SSE().PatchTempl(templates.TodoItem(todos[i]))\n        }\n    }\n    ctx.NotFound(\"Todo not found\")\n    return nil\n}\n\nfunc DeleteTodo(ctx *router.Context) error {\n    id := ctx.Param(\"id\")\n    for i := range todos {\n        if todos[i].ID == id {\n            todos = append(todos[:i], todos[i+1:]...)\n            return ctx.SSE().RemoveByID(\"todo-\" + id)\n        }\n    }\n    ctx.NotFound(\"Todo not found\")\n    return nil\n}"),
			H3("Templates"),
			CodeFile("templ", "templates/todos.templ", "package templates\n\ntempl TodoPage() {\n    @Layout(\"Todos\") {\n        <div class=\"container\">\n            <h1>My Todos</h1>\n            @TodoForm()\n            <div id=\"todo-list\">\n                for _, todo := range todos {\n                    @TodoItem(todo)\n                }\n            </div>\n        </div>\n    }\n}\n\ntempl TodoForm() {\n    <form\n        data-signals=\"{title: ''}\"\n        data-on:submit__prevent=\"@post('/todos')\"\n        class=\"todo-form\"\n    >\n        <input\n            type=\"text\"\n            data-bind:title\n            placeholder=\"What needs to be done?\"\n            required\n            autofocus\n        />\n        <button type=\"submit\">Add</button>\n    </form>\n}\n\ntempl TodoItem(todo Todo) {\n    <div id={ \"todo-\" + todo.ID } class=\"todo-item\">\n        <input\n            type=\"checkbox\"\n            checked?={ todo.Done }\n            data-on:click={ \"@patch('/todos/\" + todo.ID + \"')\" }\n        />\n        <span class={ templ.KV(\"completed\", todo.Done) }>\n            { todo.Title }\n        </span>\n        <button\n            data-on:click={ \"@delete('/todos/\" + todo.ID + \"')\" }\n            class=\"delete-btn\"\n        >\n            x\n        </button>\n    </div>\n}\n\ntempl TodoList(todos []Todo) {\n    for _, todo := range todos {\n        @TodoItem(todo)\n    }\n    if len(todos) == 0 {\n        <p class=\"empty-state\">No todos yet. Add one above!</p>\n    }\n}"),
			H3("Routes"),
			CodeFile("go", "app/app.go", "func NewRouter() *router.Router {\n    r := router.New()\n\n    r.GET(\"/\", handlers.TodoPage)      // Full page render\n    r.DSPost(\"/todos\", handlers.CreateTodo)\n    r.DSPatch(\"/todos/{id}\", handlers.ToggleTodo)\n    r.DSDelete(\"/todos/{id}\", handlers.DeleteTodo)\n\n    return r\n}"),
			H2("Search with Debounce"),
			P("Real-time search with debounced input using Datastar modifiers."),
			CodeFile("templ", "templates/search.templ", "templ SearchPage() {\n    @Layout(\"Search\") {\n        <div class=\"search-container\" data-signals=\"{query: '', loading: false}\">\n            <input\n                type=\"text\"\n                data-bind:query\n                data-on:keyup__debounce.300ms=\"$loading = true; @get('/search')\"\n                placeholder=\"Search users...\"\n            />\n            <span data-show=\"$loading\" class=\"spinner\">Searching...</span>\n            <div id=\"results\"></div>\n        </div>\n    }\n}\n\ntempl SearchResults(users []User, query string) {\n    if len(users) == 0 {\n        <p class=\"no-results\">No users found for \"{ query }\"</p>\n    } else {\n        <ul class=\"user-list\">\n            for _, user := range users {\n                @UserCard(user)\n            }\n        </ul>\n    }\n}"),
			CodeFile("go", "handlers/search.go", "func Search(ctx *router.Context) error {\n    var signals struct {\n        Query string `json:\"query\"`\n    }\n    ctx.ReadSignals(&signals)\n\n    if signals.Query == \"\" {\n        return nil\n    }\n\n    users := searchUsers(signals.Query)\n\n    sse := ctx.SSE()\n    sse.PatchTempl(templates.SearchResults(users, signals.Query))\n    sse.PatchSignals(map[string]any{\"loading\": false})\n    return nil\n}"),
			H2("Modal Dialog"),
			P("A reusable modal pattern using Datastar signals for state."),
			CodeFile("templ", "templates/modal.templ", "templ ModalContainer() {\n    <div data-signals=\"{showModal: false, modalAction: ''}\">\n        <div id=\"modal-container\"></div>\n    </div>\n}\n\ntempl ConfirmModal(title string, message string, action string) {\n    <div class=\"modal-backdrop\" data-show=\"$showModal\" data-on:click=\"$showModal = false\">\n        <div class=\"modal\" data-on:click__stop=\"\">\n            <h2>{ title }</h2>\n            <p>{ message }</p>\n            <div class=\"modal-actions\">\n                <button\n                    data-on:click={ fmt.Sprintf(\"@post('%s'); $showModal = false\", action) }\n                    class=\"btn-danger\"\n                >\n                    Confirm\n                </button>\n                <button\n                    data-on:click=\"$showModal = false\"\n                    class=\"btn-secondary\"\n                >\n                    Cancel\n                </button>\n            </div>\n        </div>\n    </div>\n}\n\ntempl DeleteUserButton(userID string) {\n    <button\n        data-on:click={ fmt.Sprintf(\"$modalAction = '/users/%s'; $showModal = true\", userID) }\n        class=\"btn-danger\"\n    >\n        Delete User\n    </button>\n}"),
			CodeFile("go", "handlers/modal.go", "func DeleteUser(ctx *router.Context) error {\n    userID := ctx.Param(\"id\")\n    deleteUser(userID)\n\n    sse := ctx.SSE()\n    sse.RemoveByID(\"user-\" + userID)\n    return nil\n}"),
			H2("Infinite Scroll"),
			P("Load more items as the user scrolls using Datastar's intersection observer."),
			CodeFile("templ", "templates/feed.templ", "templ Feed(posts []Post, page int, hasMore bool) {\n    <div class=\"feed\">\n        for i, post := range posts {\n            if i == len(posts)-1 && hasMore {\n                // Last item triggers loading more\n                <div data-intersect={ fmt.Sprintf(\"@get('/feed?page=%d')\", page+1) }>\n                    @PostCard(post)\n                </div>\n            } else {\n                @PostCard(post)\n            }\n        }\n        if !hasMore && len(posts) > 0 {\n            <p class=\"end-of-feed\">You've reached the end!</p>\n        }\n    </div>\n}\n\ntempl PostCard(post Post) {\n    <article class=\"post-card\">\n        <h3>{ post.Title }</h3>\n        <p>{ post.Excerpt }</p>\n        <time>{ post.CreatedAt.Format(\"Jan 2, 2006\") }</time>\n    </article>\n}"),
			H2("Tabs"),
			P("Tab navigation using Datastar signals for active state."),
			CodeFile("templ", "templates/tabs.templ", "templ TabsPage() {\n    @Layout(\"Dashboard\") {\n        <div class=\"tabs-container\" data-signals=\"{activeTab: 'overview'}\">\n            <nav class=\"tab-nav\">\n                <button\n                    data-class:active=\"$activeTab === 'overview'\"\n                    data-on:click=\"$activeTab = 'overview'; @get('/dashboard/overview')\"\n                >\n                    Overview\n                </button>\n                <button\n                    data-class:active=\"$activeTab === 'analytics'\"\n                    data-on:click=\"$activeTab = 'analytics'; @get('/dashboard/analytics')\"\n                >\n                    Analytics\n                </button>\n                <button\n                    data-class:active=\"$activeTab === 'settings'\"\n                    data-on:click=\"$activeTab = 'settings'; @get('/dashboard/settings')\"\n                >\n                    Settings\n                </button>\n            </nav>\n            <div id=\"tab-content\">\n                <!-- Content loads here -->\n            </div>\n        </div>\n    }\n}\n\ntempl OverviewTab() {\n    <div id=\"tab-content\" class=\"tab-panel\">\n        <h2>Overview</h2>\n        <p>Your dashboard overview content here.</p>\n    </div>\n}"),
			H2("Running the Examples"),
			P("Create a new irgo project and try these patterns:"),
			Code("bash", "irgo project new myapp\ncd myapp\n\ngo mod tidy\n\nirgo server dev"),
			H2("Next Steps"),
			Bullets(
				"[Getting Started](/docs/getting-started) - Create your own project",
				"[Datastar Integration](/docs/datastar) - More Datastar patterns",
				"[GitHub](https://github.com/stukennedy/irgo) - Browse the source code",
			),
		},
	},
}

// Find returns a page by slug.
func Find(slug string) (Page, bool) {
	for _, p := range Pages {
		if p.Slug == slug {
			return p, true
		}
	}
	return Page{}, false
}
