package clidoc

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// The CLI reference is generated from the CLI itself.
//
// The old site's CLI page was written by hand and drifted every time a command
// moved — it documented `irgo doctor`, `irgo dev` and `irgo ios team` long
// after all three were renamed, and never mentioned nine flags that existed.
// This file reads what the binary declares, so the page cannot describe a
// command the binary does not have.
//
// Regenerate with:  go tool irgo help --json > clidoc/cli.json
// A test fails when it is stale, so it cannot quietly fall behind.
//
//go:embed cli.json
var cliJSON []byte

// Command is one documented noun-verb pair.
type Command struct {
	Noun    string   `json:"noun"`
	Verb    string   `json:"verb"`
	Summary string   `json:"summary"`
	Targets []string `json:"targets,omitempty"`
	Args    string   `json:"args,omitempty"`
	Usage   []Usage  `json:"usage,omitempty"`
	Flags   []Flag   `json:"flags,omitempty"`
	Notes   string   `json:"notes,omitempty"`
}

type Usage struct {
	Form string `json:"form"`
	What string `json:"what"`
}

type Flag struct {
	Spec string `json:"spec"`
	What string `json:"what"`
}

// Name is the command as typed.
func (c Command) Name() string { return c.Noun + " " + c.Verb }

// Signature is the command with whatever it accepts, as the index shows it.
func (c Command) Signature() string {
	switch {
	case len(c.Targets) > 0:
		out := c.Name() + " <"
		for i, t := range c.Targets {
			if i > 0 {
				out += "|"
			}
			out += t
		}
		return out + ">"
	case c.Args != "":
		return c.Name() + " " + c.Args
	}
	return c.Name()
}

// UsageLine renders one usage form as a runnable command.
func (c Command) UsageLine(u Usage) string {
	if u.Form == "" {
		return "irgo " + c.Name()
	}
	return fmt.Sprintf("irgo %s %s", c.Name(), u.Form)
}

// CLICommands returns every command, in the order the CLI lists them.
func Commands() []Command {
	var out []Command
	if err := json.Unmarshal(cliJSON, &out); err != nil {
		// Embedded and generated by the build; a failure here means the
		// generator changed shape, which should stop the site rather than
		// render an empty page.
		panic("docs: cli.json does not parse: " + err.Error())
	}
	return out
}

// CLINouns groups the commands the way the CLI's own help does.
func Nouns() []string { return []string{"project", "app", "tools", "server"} }

// CommandsFor returns one noun's commands.
func For(noun string) []Command {
	var out []Command
	for _, c := range Commands() {
		if c.Noun == noun {
			out = append(out, c)
		}
	}
	return out
}
