// The static shell around the wasm binary: the page that boots it, the service
// worker that hosts it, and the manifest that makes it installable.
//
// Generated rather than scaffolded into the project. They are derived from the
// build the way the Worker's shim is — a project that hand-edited them would
// find the edit replaced, and there is nothing here worth owning.
package main

import "fmt"

// webIndexHTML is the page served when no service worker is controlling yet.
//
// Only ever seen once. Its whole job is to register the worker and get out of
// the way: after that the worker answers "/" from the Go router, and this file
// is not reached again unless the registration is removed.
func webIndexHTML(name string) string {
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>` + name + `</title>
<link rel="manifest" href="manifest.webmanifest">
<style>
  html { color-scheme: light dark }
  body { font: 16px/1.5 system-ui, sans-serif; display: grid; place-items: center;
         min-height: 100dvh; margin: 0 }
  .m { max-width: 34rem; padding: 2rem; text-align: center }
  code { background: color-mix(in srgb, currentColor 12%, transparent);
         padding: .1em .4em; border-radius: .3em }
</style>
</head>
<body>
<div class="m" id="status">Starting ` + name + `…</div>
<script>
  const status = document.getElementById('status');
  const fail = (msg, detail) => {
    status.innerHTML = '<h1>' + msg + '</h1><p>' + detail + '</p>';
  };

  if (!('serviceWorker' in navigator)) {
    // Not a browser limitation so much as a context one: this is what an
    // insecure origin looks like from in here.
    fail('This needs a service worker',
      'Your browser did not offer one. That usually means the page is not on ' +
      'https and not on localhost — service workers require a secure context, ' +
      'and the whole app is served by one.');
  } else {
    navigator.serviceWorker.register('sw.js').then(async () => {
      await navigator.serviceWorker.ready;

      // The worker installs but does not control the page that registered it
      // until a navigation. clients.claim() in the worker covers most of it;
      // reloading covers the first ever load, where this page came off the
      // network before the worker existed.
      if (!navigator.serviceWorker.controller) {
        location.reload();
        return;
      }
      location.replace('/');
    }).catch(err => {
      fail('Could not start', 'The service worker failed to register: ' + err);
    });
  }
</script>
</body>
</html>
`
}

// webServiceWorkerJS hosts the Go router.
//
// The fetch listener is registered synchronously, at the top level, before the
// wasm has loaded — that is a requirement rather than a style choice. A worker
// only takes control of requests if it registers a fetch listener during the
// initial evaluation of its script, and instantiating wasm is asynchronous. A
// listener added after the await would install a worker that controls nothing:
// every request would go to the network, and with no server there, the app
// would simply not load.
func webServiceWorkerJS() string {
	return `// Generated by irgo. The Go router runs in here.
importScripts('wasm_exec.js');

const CACHE = 'irgo-shell-v1';

// The three files needed to start. Everything else — pages, stylesheets,
// images — comes out of the wasm binary, so there is nothing else to cache.
const SHELL = ['wasm_exec.js', 'app.wasm', 'manifest.webmanifest'];

// Kick off wasm as the script evaluates, and remember the promise. Requests
// that arrive before it settles wait on it rather than falling through to a
// network that may not be there.
const ready = (async () => {
  const go = new Go();
  const result = await WebAssembly.instantiateStreaming(fetch('app.wasm'), go.importObject);

  // Not awaited: the Go main blocks forever so the router stays up, so its
  // promise never settles. Control returns here once main blocks, by which
  // point it has exported __irgoFetch.
  go.run(result.instance);

  if (typeof self.__irgoFetch !== 'function') {
    throw new Error('the wasm binary did not export __irgoFetch');
  }
})();

self.addEventListener('install', (event) => {
  // Cache the shell so a second visit needs no network at all.
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(SHELL);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key);
    }
    // Control the pages that are already open, including the one that
    // registered this worker.
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Anything on another origin is not ours to answer.
  if (url.origin !== self.location.origin) return;

  // The boot files are real files. Serving them from the Go router would mean
  // the router had to know about its own bootstrap, and the wasm binary cannot
  // serve the wasm binary.
  const name = url.pathname.replace(/^\//, '');
  if (SHELL.includes(name)) {
    event.respondWith(caches.match(event.request).then(hit => hit || fetch(event.request)));
    return;
  }

  event.respondWith((async () => {
    try {
      await ready;
      return await self.__irgoFetch(event.request);
    } catch (err) {
      return new Response('irgo: ' + err, {
        status: 500,
        headers: { 'content-type': 'text/plain' },
      });
    }
  })());
});
`
}

// webManifest makes it installable, which is the difference between a page
// that happens to work offline and an app.
func webManifest(name string) string {
	return fmt.Sprintf(`{
  "name": %q,
  "short_name": %q,
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#ffffff"
}
`, name, name)
}
