// Telling each platform which languages the app has.
//
// Translations are not only text. Every output irgo produces has a manifest,
// and two of them carry language metadata the platform reads before a single
// line of the app runs:
//
//	iOS      Info.plist CFBundleLocalizations — what the App Store lists the
//	         app as supporting, and what the system offers it
//	browser  manifest.webmanifest lang and dir — the install prompt and the
//	         app name, announced before the app is opened
//
// Neither is derivable from the other and neither is visible in testing: an
// app translated into four languages ships declaring one, is listed as
// English-only in every store front, and works perfectly for anyone who
// already found it.
//
// The catalogs are the single source, the way they are for everything else
// here. A list of locales in a plist and another in a manifest would be the
// two-lists bug in its third and fourth forms — and these are the versions
// nobody would notice, because being wrong costs discoverability rather than
// correctness.
//
// Synced on every build rather than written once at scaffold time. `irgo i18n
// add fr` changes the answer, and a manifest that only knows what was true on
// the day the project was created is a manifest that is wrong from the second
// language onward.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// syncI18nManifests updates whatever manifests this project has.
//
// Silent and skipping for a project without translations, and for targets that
// have not been scaffolded — most projects have not generated every shell.
func syncI18nManifests() error {
	if !hasI18n() {
		return nil
	}
	locales := projectLocales()
	if len(locales) == 0 {
		return nil
	}
	for _, path := range []string{
		"ios/Example/Example/Info.plist",
		"ios/App/Info.plist",
	} {
		if err := setPlistLocalizations(path, locales); err != nil {
			return err
		}
	}
	return writeAndroidLocaleConfig(locales)
}

// writeAndroidLocaleConfig declares the app's languages to Android.
//
// This is the counterpart of CFBundleLocalizations, and not — as it first
// appears — res/values-de/strings.xml. That file localises the app's LABEL and
// any Android resource strings, of which an irgo app has none: every word it
// shows comes from Go through toki, and the label is usually a brand nobody
// wants translated.
//
// locales_config is what makes the app appear in Settings > Apps > (app) >
// Language, the per-app language picker Android 13 added. Without it the entry
// is simply absent, and a user who wants this one app in German while their
// phone stays in English has no way to say so.
//
// It works end to end because IrgoActivity already reads
// resources.configuration.locales, which is where Android puts the per-app
// override — so the picker reaches toki with nothing else to wire.
//
// Neither this nor the plist is required for the stores to accept a build.
// What they cost is discoverability and control, which is why their absence
// survives every test.
func writeAndroidLocaleConfig(locales []string) error {
	const dir = "android/Example/app/src/main/res/xml"
	manifest := "android/Example/app/src/main/AndroidManifest.xml"
	if !pathExists(manifest) {
		return nil // the Android shell has not been generated
	}

	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="utf-8"?>` + "\n")
	b.WriteString(`<!-- Generated by irgo from tokibundle/. Do not edit. -->` + "\n")
	b.WriteString(`<locale-config xmlns:android="http://schemas.android.com/apk/res/android">` + "\n")
	for _, l := range locales {
		fmt.Fprintf(&b, "    <locale android:name=%q/>\n", l)
	}
	b.WriteString("</locale-config>\n")

	path := filepath.Join(dir, "locales_config.xml")
	if have, err := os.ReadFile(path); err == nil && string(have) == b.String() {
		return referenceLocaleConfig(manifest)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return referenceLocaleConfig(manifest)
}

// referenceLocaleConfig points the manifest at the file, once.
//
// Written here rather than in the template because the file it names must not
// be referenced when it does not exist — aapt2 fails the build on a missing
// resource, so a project without translations would stop compiling.
func referenceLocaleConfig(manifest string) error {
	body, err := os.ReadFile(manifest)
	if err != nil {
		return nil
	}
	text := string(body)
	if strings.Contains(text, "android:localeConfig") {
		return nil
	}
	const anchor = `android:label="@string/app_name"`
	i := strings.Index(text, anchor)
	if i < 0 {
		return nil // not a manifest shape irgo recognises
	}
	at := i + len(anchor)
	text = text[:at] + "\n        android:localeConfig=\"@xml/locales_config\"" + text[at:]
	return os.WriteFile(manifest, []byte(text), 0o644)
}

// plistLocalizations matches the array this writes, so re-running replaces it
// rather than appending a second one — which is valid XML and undefined
// behaviour in a plist.
var plistLocalizations = regexp.MustCompile(
	`(?s)\n\t<key>CFBundleLocalizations</key>\n\t<array>.*?\n\t</array>`)

// setPlistLocalizations declares the app's languages to iOS.
//
// Without it the App Store lists the app as supporting only its development
// region. The translations still work for anyone who has the app — this is
// entirely about whether a German speaker searching the store is shown it as a
// German app, which is the difference between the translations being read and
// not.
func setPlistLocalizations(path string, locales []string) error {
	body, err := os.ReadFile(path)
	if err != nil {
		return nil // this shell has not been generated
	}
	text := string(body)

	var b strings.Builder
	b.WriteString("\n\t<key>CFBundleLocalizations</key>\n\t<array>")
	for _, l := range locales {
		// BCP 47 in the catalogs, and that is what iOS wants here too — it
		// accepts "pt-BR" as readily as "pt".
		fmt.Fprintf(&b, "\n\t\t<string>%s</string>", l)
	}
	b.WriteString("\n\t</array>")
	want := b.String()

	switch {
	case plistLocalizations.MatchString(text):
		if plistLocalizations.FindString(text) == want {
			return nil // already correct; do not rewrite and dirty the tree
		}
		text = plistLocalizations.ReplaceAllString(text, want)
	default:
		// After the opening <dict>, so the file stays readable. Order is not
		// significant in a plist, but a key appended after the closing tag
		// would simply be outside the dictionary and silently ignored.
		const anchor = "<dict>"
		i := strings.Index(text, anchor)
		if i < 0 {
			return nil // not a plist shape irgo recognises
		}
		at := i + len(anchor)
		text = text[:at] + want + text[at:]
	}
	return os.WriteFile(path, []byte(text), 0o644)
}

func init() {
	// After the bundle is regenerated, so the locale list is the one this
	// build actually produced rather than the one before `irgo i18n add`.
	registerAssetStep(assetOrderLate, syncI18nManifests)
}
